// models_multiplayer.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 27 total shaders
// Modified - Rich 30-04-03


models/multiplayer/satchel/radio
{
	///etl/// maxpicmip 1
	{
				map textures/effects/envmap_slate_90.tga
				rgbGen lightingdiffuse
				tcGen environment
	}
	{
				map models/multiplayer/satchel/radio.tga
				blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
				rgbGen lightingdiffuse
	}
}



models/multiplayer/satchel/satchel_allied
{
	///etl/// maxpicmip 1
	{
				map textures/effects/envmap_slate.tga
				rgbGen lightingdiffuse
				tcGen environment
	}
	{
				map models/multiplayer/satchel/satchel_allied.tga
				blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
				rgbGen lightingdiffuse
	}
}

models/multiplayer/satchel/satchel_axis
{
	///etl/// maxpicmip 1
	{
				map textures/effects/envmap_slate_90.tga
				rgbGen lightingdiffuse
				tcGen environment
	}
	{
				map models/multiplayer/satchel/satchel_axis.tga
				blendFunc blend
				rgbGen lightingdiffuse
	}
}



models/multiplayer/satchel/light_ref
{
	///etl/// maxpicmip 1
	{
		map textures/effects/tinfx.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/satchel/lightoff.tga
		blendFunc blend
		rgbGen lightingdiffuse
	}
}


models/multiplayer/satchel/lightgreen_off
{
	///etl/// maxpicmip 1
	{
		map models/multiplayer/satchel/lightoff.tga
		rgbgen lightingdiffuse
	}
}


models/multiplayer/satchel/lightgreen_off
{
	///etl/// maxpicmip 1
	{
		map models/multiplayer/satchel/lightoff.tga
		rgbgen lightingdiffuse
	}
}

models/multiplayer/satchel/lightgreen_on
{
	///etl/// maxpicmip 1
	{
		map models/multiplayer/satchel/lightoff.tga
		rgbgen lightingdiffuse
	}
	{
		map models/multiplayer/satchel/lightgreen.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.2 0.8 0.5 10

	}
}
models/multiplayer/satchel/lightred_off
{
	///etl/// maxpicmip 1
	{
		map models/multiplayer/satchel/lightoff.tga
		rgbgen lightingdiffuse
	}
}

models/multiplayer/satchel/lightred_on
{
	///etl/// maxpicmip 1
	{
		map models/multiplayer/satchel/lightoff.tga
		rgbgen lightingdiffuse
	}
	{
		map models/multiplayer/satchel/lightred.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.2 0.8 0.3 9

	}
}

models/multiplayer/supplies/healthbox
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate_90.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/supplies/healthbox.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/supplies/ammobox
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate_90.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/supplies/ammobox.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/supplies/ammobox_2
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate_90.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/supplies/ammobox_2.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/smokebomb/smoke_bomb
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate_90.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/smokebomb/smoke_bomb.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/smokegrenade/smoke_grenade
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate_90.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/smokegrenade/smoke_grenade.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}


models/multiplayer/landmine/landmine
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate_90.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/landmine/landmine.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/pliers/pliers
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate_90.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/pliers/pliers.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/binocs/binoculars
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/binocs/binoculars.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/mortar/mortar_sd
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/mortar/mortar_sd.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}


models/multiplayer/mg42/s_mg42
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/mg42/s_mg42.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}



models/multiplayer/browning/handle
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/browning/handle.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/browning/browning
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/browning/browning.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/browning/barrel
{
	///etl/// maxpicmip 1
	cull none
	{
		map models/multiplayer/browning/barrel.tga
		rgbGen const ( 0 0 0 )
		alphaFunc GE128
		depthWrite
	}
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
		depthFunc equal
	}
	{
		map models/multiplayer/browning/barrel.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
		depthFunc equal
	}
}

models/multiplayer/gold/gold
{
	///etl/// maxpicmip 1
	{
		map models/multiplayer/gold/gold.tga
		rgbGen lightingdiffuse
	}
	{
		map textures/effects/envmap_gold.tga
		blendFunc GL_ONE GL_ONE
		tcMod scale 2.25 1.25
		tcGen environment
		rgbGen lightingdiffuse
	}
}

models/multiplayer/treasure/treasure
{
	///etl/// maxpicmip 1
	cull disable
	deformvertexes autosprite
	sort nearest
	surfaceparm trans
	{
		map models/multiplayer/treasure/treasure.tga
		blendfunc gl_src_alpha gl_one_minus_src_alpha
		tcmod stretch sin .8 .08 0 .8
	}
}

models/multiplayer/flagpole/american
{
	///etl/// maxpicmip 1
	cull disable
//	deformVertexes wave 194 sin 0 3 0 .4
	{
		map models/multiplayer/flagpole/american.tga
		rgbGen lightingDiffuse
	}
}

models/multiplayer/flagpole/american_reinforce
{
	///etl/// maxpicmip 1
	cull disable
//	deformVertexes wave 194 sin 0 3 0 .4
	{
		map models/multiplayer/flagpole/american_reinforce.tga
		rgbGen lightingDiffuse
	}
}

models/multiplayer/flagpole/disc
{
	///etl/// maxpicmip 1
	{
		clampmap models/multiplayer/flagpole/disc.tga
		rgbGen lightingDiffuse
		tcMod rotate 30
		blenfunc blend
	}
}

models/multiplayer/flagpole/flagpole
{
	///etl/// maxpicmip 1
	{
		map models/multiplayer/flagpole/flag_clouds.tga
		rgbGen lightingDiffuse
		tcgen environment
	}
}

models/multiplayer/flagpole/german
{
	///etl/// maxpicmip 1
	cull disable
//	deformVertexes wave 194 sin 0 3 0 .4
	{
		map models/multiplayer/flagpole/german.tga
		rgbGen lightingDiffuse
	}
}

models/multiplayer/flagpole/german_reinforce
{
	///etl/// maxpicmip 1
	cull disable
//	deformVertexes wave 194 sin 0 3 0 .4
	{
		map models/multiplayer/flagpole/german_reinforce.tga
		rgbGen lightingDiffuse
	}
}

models/multiplayer/flagpole/waypoint
{
	///etl/// maxpicmip 1
	cull disable
	deformVertexes wave 194 sin 0 3 0 .4
	{
		map models/multiplayer/flagpole/waypoint.tga
		rgbGen lightingDiffuse
	}
}

models/multiplayer/kar98/kar98silencer
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/m1_garand/m1garandsilencer_yd.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/kar98/mauser3
{
	///etl/// maxpicmip 1
     {
          map textures/effects/envmap_slate.tga
          rgbGen lightingdiffuse
          tcGen environment
     }
     {
          map models/weapons2/mauser/mauser3_yd.tga
          blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
          rgbGen lightingdiffuse
     }
}

models/multiplayer/mg42/bullet
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_gold.tga
		rgbGen identity
		tcGen environment
	}
	{
		map models/multiplayer/mg42/bullet_yd.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen lightingdiffuse
	}
}

models/multiplayer/mine_marker/allied_marker
{
	cull disable
	nomipmaps
	nopicmip
	{
		map models/multiplayer/mine_marker/allied_marker.tga
		rgbGen lightingdiffuse
	}
}

models/multiplayer/mine_marker/axis_marker
{
	cull disable
	nomipmaps
	nopicmip
	{
		map models/multiplayer/mine_marker/axis_marker.tga
		rgbGen lightingdiffuse
	}
}

models/multiplayer/m1_garand/m1_garand
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/m1_garand/m1_garand_yd.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/m1_garand/m1garandscope
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/m1_garand/m1garandscope_yd.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/m1_garand/m1garandsilencer
{
	///etl/// maxpicmip 1
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/m1_garand/m1garandsilencer_yd.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}

models/multiplayer/syringe/adrenaline
{
	///etl/// maxpicmip 1
	cull disable
	{
		map models/multiplayer/syringe/fluid2.tga
		blendfunc blend
		rgbgen lightingdiffuse
		tcmod scale 4 6
		tcmod scroll 0 -.8
	}
	{
		map models/multiplayer/syringe/syringe.tga
		blendfunc gl_src_alpha gl_one_minus_src_alpha
		rgbgen lightingdiffuse
	}
	{
		map models/multiplayer/syringe/syringe_reflections.tga
		blendfunc gl_src_alpha gl_one_minus_src_alpha
		rgbgen lightingdiffuse
	}
}

models/multiplayer/syringe/plunger
{
	///etl/// maxpicmip 1
	{
		map models/multiplayer/syringe/plunger.tga
		rgbgen lightingdiffuse
	}
}

models/multiplayer/syringe/syringe
{
	///etl/// maxpicmip 1
	cull disable
	{
		map models/multiplayer/syringe/fluid.tga
		blendfunc blend
		rgbgen lightingdiffuse
		tcmod scale 4 6
		tcmod scroll 0 -.8
	}
	{
		map models/multiplayer/syringe/syringe.tga
		blendfunc gl_src_alpha gl_one_minus_src_alpha
		rgbgen lightingdiffuse
	}
	{
		map models/multiplayer/syringe/syringe_reflections.tga
		blendfunc gl_src_alpha gl_one_minus_src_alpha
		rgbgen lightingdiffuse
	}
}

models/multiplayer/syringe/100percent
{
	///etl/// maxpicmip 1
	cull disable
	{
		map models/multiplayer/syringe/fluid3.tga
		blendfunc blend
		rgbgen lightingdiffuse
		tcmod scale 4 6
		tcmod scroll 0 -.8
	}
	{
		map models/multiplayer/syringe/syringe.tga
		blendfunc gl_src_alpha gl_one_minus_src_alpha
		rgbgen lightingdiffuse
	}
	{
		map models/multiplayer/syringe/syringe_reflections.tga
		blendfunc gl_src_alpha gl_one_minus_src_alpha
		rgbgen lightingdiffuse
	}
}

models/multiplayer/test/alliedflag
{
	nocompress
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/alliedflag.tga
	}
	{
		map ui/assets/portraits/stars.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		tcMod scroll -.125 -.125
	}
	{
		map ui/assets/portraits/medic.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

models/multiplayer/test/axisflag
{
	nocompress
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/axisflag.tga
	}
	{
		map ui/assets/portraits/wolflogo.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		tcMod scroll 0.125 0
	}
	{
		map ui/assets/portraits/medic_ger.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}
