/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_n0n3m4_q3e_Q3EJNI */

#ifndef _Included_com_n0n3m4_q3e_Q3EJNI
#define _Included_com_n0n3m4_q3e_Q3EJNI
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_setCallbackObject
  (JNIEnv *, jclass, jobject);

JNIEXPORT jboolean JNICALL Java_com_n0n3m4_q3e_Q3EJNI_init
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jstring, jstring, jstring, jobject, jint, jint, jint, jboolean, jboolean, jboolean, jboolean, jint, jstring, jboolean, jboolean);

JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_drawFrame
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_sendKeyEvent
  (JNIEnv *, jclass, jint, jint, jint);

JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_sendMotionEvent
  (JNIEnv *, jclass, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_sendAnalog(JNIEnv *env, jclass c, jint enable, jfloat x, jfloat y);

JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_vidRestart
  (JNIEnv *, jclass);    
  
JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_setRenderer
  (JNIEnv *env, jclass c, jobject obj);

JNIEXPORT jboolean JNICALL Java_com_n0n3m4_q3e_Q3EJNI_Is64
  (JNIEnv *env, jclass c);
  
JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_shutdown(JNIEnv *env, jclass c);

JNIEXPORT void JNICALL
Java_com_n0n3m4_q3e_Q3EJNI_OnPause(JNIEnv *env, jclass clazz);

JNIEXPORT void JNICALL
Java_com_n0n3m4_q3e_Q3EJNI_OnResume(JNIEnv *env, jclass clazz);

JNIEXPORT void JNICALL
Java_com_n0n3m4_q3e_Q3EJNI_SetSurface(JNIEnv *env, jclass clazz, jobject view);

JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_PushKeyEvent
(JNIEnv *, jclass, jint, jint, jint);

JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_PushMotionEvent
(JNIEnv *, jclass, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_PushAnalogEvent(JNIEnv *env, jclass c, jint enable, jfloat x, jfloat y);

JNIEXPORT void JNICALL Java_com_n0n3m4_q3e_Q3EJNI_PreInit
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif



