/*
 * Wolfenstein: Enemy Territory GPL Source Code
 * Copyright (C) 1999-2010 id Software LLC, a ZeniMax Media company.
 *
 * ET: Legacy
 * Copyright (C) 2012-2024 ET:Legacy team <mail@etlegacy.com>
 *
 * This file is part of ET: Legacy - http://www.etlegacy.com
 *
 * ET: Legacy is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ET: Legacy is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ET: Legacy. If not, see <http://www.gnu.org/licenses/>.
 *
 * In addition, Wolfenstein: Enemy Territory GPL Source Code is also
 * subject to certain additional terms. You should have received a copy
 * of these additional terms immediately following the terms and conditions
 * of the GNU General Public License which accompanied the source code.
 * If not, please request a copy in writing from id Software at the address below.
 *
 * id Software LLC, c/o ZeniMax Media Inc., Suite 120, Rockville, Maryland 20850 USA.
 */

#include "etl_version.h"

/// Generated by CMake in the build directory
#include <git_version.h>

/* Exported constants initialized from macros */
const char etlegacy_modname[] = MODNAME;
const char etlegacy_modurl[]  = MODURL;
const char etlegacy_omnibot_modname[] = MODNAME "/omni-bot";

const char etlegacy_version[]       = ETLEGACY_VERSION;
const char etlegacy_version_short[] = ETLEGACY_VERSION_SHORT;

const unsigned long etlegacy_version_int = (unsigned long)ETLEGACY_VERSION_INT;

const int  etlegacy_product_version[4]    = { PRODUCT_VERSION };
const char etlegacy_product_version_str[] = PRODUCT_VERSION_STR;

const char etlegacy_product_build_time[]     = PRODUCT_BUILD_TIME;
const char etlegacy_product_build_features[] = PRODUCT_BUILD_FEATURES;

// ---

#define Q3_VERSION              PRODUCT_LABEL " " ETLEGACY_VERSION

#ifdef ETLEGACY_DEBUG
#define ET_VERSION              Q3_VERSION " " CPUSTRING " " __DATE__ " DEBUG"
#else
#define ET_VERSION              Q3_VERSION " " CPUSTRING " " __DATE__
#endif

const char q3_version[] = Q3_VERSION;
const char et_version[] = ET_VERSION;
