//==========================================================================
//
// Character Animation Script     M U L T I P L A Y E R
//
// This defines the animations and events that might occur at different times
// for this character. State changes, and random behaviour during idle/alert
// states will look here for default behaviour, if that character doesn't have
// something specific in their scripts for that level.
//
//==========================================================================
// DEFINES
//
// These can be used to simplify the scripting, by defining replacement strings

DEFINES

// weapons
set weapons knives               = Knife AND Ka-Bar
set weapons Bipods               = Mobile MG 42 Bipod AND Mobile Browning Bipod
set weapons pistols              = Luger AND Colt AND Silenced Luger AND Silenced Colt
set weapons akimbo_pistols       = Akimbo Luger AND Silenced Akimbo Luger AND Akimbo Colt AND Silenced Akimbo Colt
set weapons machineguns          = MP 40 AND Thompson AND Sten gun AND Flamethrower AND panzerfaust AND bazooka AND Mobile MG 42 AND Mobile Browning AND MP34
set weapons rifles               = K43 Rifle AND gpg40 AND M7 AND m1 garand AND FG 42 Paratroop Rifle AND Scoped K43 Rifle AND K43 Rifle Scope AND M1 Garand Scope AND FG 42 Paratroop Rifle Scope

// broke off dynamite, since we never want to throw it overhand
set weapons throwables           = pineapple AND grenade AND Smoke Bomb
set weapons throwables_underhand = dynamite weapon

set weapons one_handed_weapons   = Luger AND Colt AND Silenced Luger AND Silenced Colt
set weapons two_handed_weapons   = MP 40 AND Thompson AND Sten gun AND flamethrower AND panzerfaust AND bazooka AND K43 Rifle AND gpg40 AND M7 AND m1 garand AND FG 42 Paratroop Rifle AND Scoped M1 Garand AND Mobile MG 42 AND Scoped K43 Rifle AND K43 Rifle Scope AND M1 Garand Scope AND FG 42 Paratroop Rifle Scope AND Mobile Browning AND MP34

set weapons all                    = Luger AND Colt AND Silenced Luger AND Silenced Colt AND Binoculars AND special AND Ammo Pack AND knives AND dynamite weapon AND pineapple AND grenade AND smokeGrenade AND Smoke Bomb AND Landmine AND Satchel Charge AND MP 40 AND Thompson AND Sten gun AND flamethrower AND panzerfaust AND bazooka AND Ammo Pack AND Medicheal AND gpg40 AND M7 AND m1 garand AND FG 42 Paratroop Rifle AND Scoped M1 Garand AND Satchel Charge AND Landmine AND Mobile MG 42 AND Scoped K43 Rifle AND K43 Rifle Scope AND M1 Garand Scope AND FG 42 Paratroop Rifle Scope AND Mortar AND Mounted Mortar AND Satchel Charge AND Satchel Charge Detonator AND Mobile Browning AND Granatwerfer AND Mounted Granatwerfer AND MP34
set weapons all_one_handed_weapons = Luger AND Colt AND Silenced Luger AND Silenced Colt AND Binoculars AND special AND Ammo Pack AND knives AND dynamite weapon AND pineapple AND grenade AND smokeGrenade AND Smoke Bomb AND Landmine AND Satchel Charge
set weapons all_two_handed_weapons = MP 40 AND Thompson AND Sten gun AND flamethrower AND panzerfaust AND bazooka AND Ammo Pack AND Medicheal AND gpg40 AND M7 AND m1 garand AND FG 42 Paratroop Rifle AND Scoped M1 Garand AND Satchel Charge AND Landmine AND Mobile MG 42 AND Scoped K43 Rifle AND K43 Rifle Scope AND M1 Garand Scope AND FG 42 Paratroop Rifle Scope AND Mortar AND Mounted Mortar AND Satchel Charge AND Satchel Charge Detonator AND Mobile Browning AND Granatwerfer AND Mounted Granatwerfer AND MP34

// movetypes
set movetype moving = walk AND walkcr AND walkcrbk AND walkbk AND run AND runbk AND straferight AND strafeleft
set movetype crouching = idlecr AND walkcr AND walkcrbk
set movetype backstep = walkbk AND runbk AND walkcrbk
set movetype proning = idleprone AND prone AND pronebk

//==========================================================================
// ANIMATIONS
//
//	NOTE: scripts are chosen by first-come-first-serve basis. The first match
//	found is the one used.
//
// format:
//
// state <state description>
// {
//		<movement type>
//		{
//			[DEFAULT / <condition type> [<condition value>], ...]
//			{
//				<both/legs/torso> <animation> [sound <filename>]
//				<both/legs/torso> <animation> [sound <filename>]
//				...
//			}
//		}
//	}
//
//	legend:
//
//	<state description>: relaxed, alert, combat
//
//	<movement type>: dead, idle, idlecr, walk, walkbk, walkcr, walkcrbk, run, runbk, straferight, strafeleft, turnright, turnleft
//
//	<condition type>: weapons, position, enemy_weapon, underwater, mounted, movetype, underhand, leaning
//
//	<condition value>:
//
//		weapons: <see weapon pickup names>
//		position: behind, infront, right, left
//		enemy_weapon: <see weapon pickup names>
//		underwater: <no values>
//		mounted: MG42
//		movetype: <see movement types>
//		underhand: <no values>
//		leaning: right, left
//

ANIMATIONS

STATE RELAXED
{
}

STATE ALERT
{
}

STATE COMBAT
{
	dead	
	{
		suicide
		{
			both dead_rifle_head_2
		}
	
		default
		{
			both dead_machinegun_1
		}
	}

	idle
	{
		weapons Mortar AND Granatwerfer
		{
			legs stand_panzer torso e_mortar_stand
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons Satchel Charge
		{
			both stand_medpack
		}
		weapons satchel charge detonator
		{
			legs stand_medpack torso satchel_remote_stand
		}
		mounted MG42, firing
		{
			both firing_mg42
		}
		mounted MG42
		{
			both stand_mg42
		}
		weapons none
		{
			both stand_grenade
		}
		weapons Binoculars, gen_bitflag zooming
		{
			torso stand_binoculars legs stand_grenade
		}
		weapons Binoculars
		{
			both stand_grenade
		}
		weapons smokeGrenade
		{
			both stand_grenade
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both stand_knife
		}
		weapons Ammo Pack AND Landmine
		{
			both stand_medpack
		}
		weapons Satchel Charge
		{
			both stand_medpack
		}
		weapons medicheal
		{
			both stand_medpack
		}
		weapons special
		{
			both stand_knife
		}
		weapons throwables, gen_bitflag holding
		{
			both holding_grenadeA
			both holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			both stand_grenade
		}
		weapons knives
		{
			both stand_knife
		}
		weapons pistols, firing
		{
			legs firing_pistolB_1 torso stand_pistolB
			legs firing_pistolB_2 torso stand_pistolB
		}
		weapons pistols
		{
			both stand_pistolB
		}
		weapons akimbo_pistols, firing
		{
			legs firing_pistolB_1 torso stand_akimbo
			legs firing_pistolB_2 torso stand_akimbo
		}
		weapons akimbo_pistols
		{
			legs stand_pistolB torso stand_akimbo
		}
		weapons Scoped M1 Garand
		{
			both stand_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both stand_srifle
		}
		weapons K43 Rifle
		{
			both stand_srifle
		}
		weapons gpg40
		{
			legs stand_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs stand_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both stand_srifle
		}
		weapons Scoped K43 Rifle
		{
			both stand_srifle
		}
		weapons K43 Rifle Scope
		{
			both stand_rifle
		}
		weapons M1 Garand Scope
		{
			both stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			both stand_rifle
		}
		weapons bazooka
		{
			legs stand_panzer torso stand_rifle
		}
		weapons panzerfaust, firing
		{
			legs firing_panzer torso stand_panzer
		}
		weapons panzerfaust
		{
			both stand_panzer
		}
		weapons Mobile MG 42 AND Mobile Browning, firing
		{
			legs firing_machinegun torso firing_mobilemg42
		}
		weapons Mobile MG 42 AND Mobile Browning
		{
			legs stand_machinegun torso stand_mobilemg42
		}
		weapons machineguns, firing
		{
			legs firing_machinegun torso stand_machinegun
		}
		weapons machineguns
		{
			both stand_machinegun
		}
	}
	idlecr
	{
		weapons Mortar AND Granatwerfer
		{
			legs alert_crchidle_2h torso e_mortar_stand
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_crchidle_1h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_crchidle_2h torso satchel_remote_stand
		}
		weapons none
		{
			legs alert_crchidle_1h torso relaxed_idle_no
		}
		weapons Binoculars, gen_bitflag zooming
		{
			torso stand_binoculars legs alert_crchidle_1h
		}
		weapons smokeGrenade AND binoculars
		{
			legs alert_crchidle_1h torso stand_grenade
		}
		weapons Syringe AND Adrenaline Syringe
		{
			legs alert_crchidle_1h torso stand_knife
		}
		weapons Ammo Pack
		{
			legs alert_crchidle_1h torso stand_medpack
		}
		weapons Landmine
		{
			legs alert_crchidle_1h torso stand_grenade
		}
		weapons Satchel Charge
		{
			legs alert_crchidle_1h torso stand_medpack
		}
		weapons medicheal
		{
			legs alert_crchidle_1h torso stand_medpack
		}
		weapons special
		{
			both alert_crchidle_1h
		}
		weapons knives
		{
			legs alert_crchidle_1h torso stand_knife
		}
		weapons one_handed_weapons
		{
			legs alert_crchidle_1h torso stand_pistolB
		}
		weapons Scoped M1 Garand
		{
			both alert_crchidle_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_crchidle_srifle
		}
		weapons K43 Rifle
		{
			both alert_crchidle_srifle
		}
		weapons gpg40
		{
			legs alert_crchidle_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_crchidle_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_crchidle_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_crchidle_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_crchidle_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_crchidle_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_crchidle_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_crchidle_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_crchidle_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			legs alert_crchidle_2h torso stand_machinegun
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_crchidle_1h torso  holding_grenadeA
			legs alert_crchidle_1h torso  holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			legs alert_crchidle_1h torso stand_grenade
		}
		weapons akimbo_pistols
		{
			legs alert_crchidle_1h torso stand_akimbo
		}
		default
		{
			both alert_crchidle_1h
		}
	}
	walk
	{
		weapons Mortar AND Granatwerfer
		{
			legs relaxed_walk_1h_1 torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs relaxed_walk_1h_1 torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs relaxed_walk_1h_1 torso satchel_remote_stand
		}
		weapons none
		{
			both relaxed_walk_1h_1
		}
		weapons Binoculars, gen_bitflag zooming
		{
			torso stand_binoculars legs relaxed_walk_1h_1
		}
		weapons smokeGrenade AND binoculars
		{
			both relaxed_walk_1h_1
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both relaxed_walk_1h_1
		}
		weapons Ammo Pack
		{
			legs relaxed_walk_1h_1 torso stand_medpack
		}
		weapons Landmine
		{
			both relaxed_walk_1h_1
		}
		weapons Satchel Charge
		{
			legs relaxed_walk_1h_1 torso stand_medpack
		}
		weapons medicheal
		{
			legs relaxed_walk_1h_1 torso stand_medpack
		}
		weapons special
		{
			both relaxed_walk_1h_1
		}
		weapons throwables, gen_bitflag holding
		{
			legs relaxed_walk_1h_1 torso holding_grenadeA
			legs relaxed_walk_1h_1 torso holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			both relaxed_walk_1h_1
		}
		weapons one_handed_weapons
		{
			legs relaxed_walk_1h_1 torso stand_pistolB
		}
		weapons Scoped M1 Garand
		{
			legs relaxed_walk_1h_1 torso stand_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			legs relaxed_walk_1h_1 torso stand_srifle
		}
		weapons K43 Rifle
		{
			legs relaxed_walk_1h_1 torso stand_srifle
		}
		weapons gpg40
		{
			legs relaxed_walk_1h_1 torso stand_grenlauncher
		}
		weapons M7
		{
			legs relaxed_walk_1h_1 torso stand_grenlauncher
		}
		weapons m1 garand
		{
			legs relaxed_walk_1h_1 torso stand_srifle
		}
		weapons Scoped K43 Rifle
		{
			legs relaxed_walk_1h_1 torso stand_srifle
		}
		weapons K43 Rifle Scope
		{
			legs relaxed_walk_1h_1 torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs relaxed_walk_1h_1 torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs relaxed_walk_1h_1 torso stand_rifle
		}
		weapons bazooka
		{
			legs relaxed_walk_1h_1 torso stand_rifle
		}
		weapons panzerfaust
		{
			legs relaxed_walk_1h_1 torso stand_panzer
		}
		weapons two_handed_weapons
		{
			legs relaxed_walk_1h_1 torso stand_machinegun
		}
		weapons akimbo_pistols
		{
			legs relaxed_walk_1h_1 torso stand_akimbo
		}
		default
		{
			both relaxed_walk_1h_1
		}
	}
	walkbk
	{
		weapons Mortar AND Granatwerfer
		{
			legs alert_bk_2h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_bk_2h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_bk_2h torso satchel_remote_stand
		}
		weapons none
		{
			both alert_bk_1h
		}
		weapons one_handed_weapons
		{
			legs alert_bk_1h torso stand_pistolb
		}
		weapons Binoculars, gen_bitflag zooming
		{
			torso stand_binoculars legs alert_bk_1h
		}
		weapons smokeGrenade AND binoculars
		{
			both alert_bk_1h
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both alert_bk_1h
		}
		weapons Ammo Pack
		{
			legs alert_bk_1h torso stand_medpack
		}
		weapons Landmine
		{
			both alert_bk_1h
		}
		weapons Satchel Charge
		{
			legs alert_bk_1h torso stand_medpack
		}
		weapons medicheal
		{
			legs alert_bk_1h torso stand_medpack
		}
		weapons special
		{
			both alert_bk_1h
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_bk_1h torso holding_grenadeA
			legs alert_bk_1h torso holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			both alert_bk_1h
		}
		weapons Scoped M1 Garand
		{
			both alert_bk_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_bk_srifle
		}
		weapons K43 Rifle
		{
			both alert_bk_srifle
		}
		weapons gpg40
		{
			legs alert_bk_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_bk_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_bk_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_bk_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_bk_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			both alert_bk_2h
		}
		weapons akimbo_pistols
		{
			legs alert_bk_2h torso stand_akimbo
		}
		default
		{
			both alert_bk_1h
		}
	}
	walkcr
	{
		weapons Mortar AND Granatwerfer
		{
			legs alert_crch_2h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_crch_2h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_crch_2h torso satchel_remote_stand
		}
		weapons none
		{
			both alert_crch_1h
		}
		weapons one_handed_weapons
		{
			both alert_crch_1h
		}
			weapons Binoculars, gen_bitflag zooming
		{
			torso stand_binoculars legs alert_crch_1h
		}
		weapons smokeGrenade AND binoculars
		{
			both alert_crch_1h
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both alert_crch_1h
		}
		weapons Ammo Pack
		{
			legs alert_crch_2h torso stand_medpack
		}
		weapons Landmine
		{
			both alert_crch_1h
		}
		weapons Satchel Charge
		{
			legs alert_crch_2h torso stand_medpack
		}
		weapons medicheal
		{
			legs alert_crch_2h torso stand_medpack
		}
		weapons special
		{
			both alert_crch_1h
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_crch_1h torso holding_grenadeA
			legs alert_crch_1h torso holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			both alert_crch_1h
		}
		weapons Scoped M1 Garand
		{
			both alert_crch_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_crch_srifle
		}
		weapons K43 Rifle
		{
			both alert_crch_srifle
		}
		weapons gpg40
		{
			legs alert_crch_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_crch_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_crch_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_crch_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_crch_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_crch_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_crch_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_crch_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_crch_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			both alert_crch_2h
		}
		weapons akimbo_pistols
		{
			legs alert_crch_2h torso stand_akimbo
		}
		default
		{
			both alert_crch_1h
		}
	}

	walkcrbk
	{
		weapons Mortar AND Granatwerfer
		{
			legs alert_crbk_2h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_crbk_2h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_crbk_2h torso satchel_remote_stand
		}
		weapons none
		{
			both alert_crbk_1h
		}
		weapons one_handed_weapons
		{
			both alert_crbk_1h
		}
		weapons Binoculars, gen_bitflag zooming
		{
			torso stand_binoculars legs alert_crbk_1h
		}
		weapons smokeGrenade AND binoculars
		{
			both alert_crbk_1h
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both alert_crbk_1h
		}
		weapons Ammo Pack
		{
			legs alert_crbk_2h torso stand_medpack
		}
		weapons Landmine
		{
			both alert_crbk_1h
		}
		weapons Satchel Charge
		{
			legs alert_crbk_2h torso stand_medpack
		}
		weapons medicheal
		{
			legs alert_crbk_2h torso stand_medpack
		}
		weapons special
		{
			both alert_crbk_1h
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_crbk_1h torso holding_grenadeA
			legs alert_crbk_1h torso holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			both alert_crbk_1h
		}
		weapons Scoped M1 Garand
		{
			both alert_crbk_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_crbk_srifle
		}
		weapons K43 Rifle
		{
			both alert_crbk_srifle
		}
		weapons gpg40
		{
			legs alert_crbk_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_crbk_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_crbk_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_crbk_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_crbk_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_crbk_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_crbk_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_crbk_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_crbk_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			both alert_crbk_2h
		}
		weapons akimbo_pistols
		{
			legs alert_crbk_2h torso stand_akimbo
		}
		default
		{
			both alert_crbk_2h
		}
	}
	run
	{
		weapons Mortar AND Granatwerfer
		{
			legs alert_run_1h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_run_1h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_run_1h torso satchel_remote_stand
		}
		weapons none
		{
			both alert_run_no
		}
		weapons Binoculars, gen_bitflag zooming
		{
			torso stand_binoculars legs alert_run_no
		}
		weapons smokeGrenade AND binoculars
		{
			both alert_run_no
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both alert_run_1h
		}
		weapons Ammo Pack
		{
			both run_medpack
		}
		weapons Landmine
		{
			both alert_run_no
		}
		weapons Satchel Charge
		{
			both run_medpack
		}
		weapons medicheal
		{
			both run_medpack
		}
		weapons special
		{
			both alert_run_1h
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_run_no torso holding_grenadeA
			legs alert_run_no torso holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			both alert_run_no
		}
		weapons one_handed_weapons
		{
			legs alert_run_1h torso stand_pistolb
		}
		weapons Scoped M1 Garand
		{
			both alert_run_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_run_srifle
		}
		weapons K43 Rifle
		{
			both alert_run_srifle
		}
		weapons gpg40
		{
			legs alert_run_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_run_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_run_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_run_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_run_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			both alert_run_2h
		}
		weapons akimbo_pistols
		{
			legs alert_run_2h torso stand_akimbo
		}
		default
		{
			both alert_run_1h
		}
	}
	runbk
	{
		weapons Mortar AND Granatwerfer
		{
			legs alert_bk_2h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_bk_2h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_bk_2h torso satchel_remote_stand
		}
		weapons none
		{
			both alert_bk_1h
		}
		weapons one_handed_weapons
		{
			legs alert_bk_1h torso stand_pistolb
		}
		weapons Binoculars, gen_bitflag zooming
		{
			torso stand_binoculars legs alert_bk_1h
		}
		weapons smokeGrenade AND binoculars
		{
			both alert_bk_1h
		}
		weapons Syringe AND Adrenaline Syringe
		{
			legs alert_bk_1h
		}
		weapons Ammo Pack
		{
			legs alert_bk_2h torso stand_medpack
		}
		weapons Landmine
		{
			both alert_bk_1h
		}
		weapons Satchel Charge
		{
			legs alert_bk_2h torso stand_medpack
		}
		weapons medicheal
		{
			legs alert_bk_2h torso stand_medpack
		}
		weapons special
		{
			both alert_bk_1h
		}
		weapons knives
		{
			both alert_bk_1h
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_bk_1h torso holding_grenadeA
			legs alert_bk_1h torso holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			both alert_bk_1h
		}
		weapons Scoped M1 Garand
		{
			both alert_bk_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_bk_srifle
		}
		weapons K43 Rifle
		{
			both alert_bk_srifle
		}
		weapons gpg40
		{
			legs alert_bk_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_bk_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_bk_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_bk_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_bk_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			both alert_bk_2h
		}
		weapons akimbo_pistols
		{
			legs alert_bk_2h torso stand_akimbo
		}
		default
		{
			both alert_bk_2h
		}
	}
	straferight
	{
		weapons Mortar AND Granatwerfer
		{
			legs alert_run_2h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_run_2h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_run_2h torso satchel_remote_stand
		}
		weapons none
		{
			both alert_run_no
		}
		weapons one_handed_weapons
		{
			legs alert_run_1h torso stand_pistolb
		}
		weapons Binoculars, gen_bitflag zooming
		{
			torso stand_binoculars legs alert_run_1h
		}
		weapons smokeGrenade and binoculars
		{
			both alert_run_no
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both alert_run_1h
		}
		weapons Ammo Pack
		{
			both run_medpack
		}
		weapons Landmine
		{
			both alert_run_no
		}
		weapons Satchel Charge
		{
			both run_medpack
		}
		weapons medicheal
		{
			both run_medpack
		}
		weapons special
		{
			both alert_run_1h
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_run_no torso holding_grenadeA
			legs alert_run_no torso holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			both alert_run_no
		}
		weapons Scoped M1 Garand
		{
			both alert_run_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_run_srifle
		}
		weapons K43 Rifle
		{
			both alert_run_srifle
		}
		weapons gpg40
		{
			legs alert_run_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_run_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_run_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_run_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_run_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			both alert_run_2h
		}
		weapons akimbo_pistols
		{
			legs alert_run_2h torso stand_akimbo
		}
		default
		{
			both alert_run_1h
		}
	}
	strafeleft
	{
		weapons Mortar AND Granatwerfer
		{
			legs alert_run_2h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_run_2h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_run_2h torso satchel_remote_stand
		}
		weapons none
		{
			both alert_run_no
		}
		weapons one_handed_weapons
		{
			legs alert_run_1h torso stand_pistolb
		}
		weapons smokeGrenade AND binoculars
		{
			both alert_run_no
		}
		weapons Binoculars, gen_bitflag zooming
		{
			torso stand_binoculars legs alert_run_1h
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both alert_run_1h
		}
		weapons Ammo Pack
		{
			both run_medpack
		}
		weapons Landmine
		{
			both alert_run_no
		}
		weapons Satchel Charge
		{
			both run_medpack
		}
		weapons medicheal
		{
			both run_medpack
		}
		weapons special
		{
			both alert_run_1h
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_run_no torso holding_grenadeA
			legs alert_run_no torso holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			both alert_run_no
		}
		weapons Scoped M1 Garand
		{
			both alert_run_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_run_srifle
		}
		weapons K43 Rifle
		{
			both alert_run_srifle
		}
		weapons gpg40
		{
			legs alert_run_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_run_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_run_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_run_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_run_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			both alert_run_2h
		}
		weapons akimbo_pistols
		{
			legs alert_run_2h torso stand_akimbo
		}
		default
		{
			both alert_run_1h
		}
	}
	swim
	{
		weapons none
		{
			both e_swim_1h
		}
		weapons all_two_handed_weapons
		{
			both e_swim_2h
		}
		weapons all_one_handed_weapons
		{
			both e_swim_1h
		}
		default
		{
			both e_swim_1h
		}
	}
	swimbk
	{
		weapons none
		{
			both e_swim_1h
		}
		weapons all_two_handed_weapons
		{
			both e_swim_2h
		}
		weapons all_one_handed_weapons
		{
			both e_swim_1h
		}
		default
		{
			both e_swim_1h
		}
	}
	climbup
	{
		default
		{
			both climb_up
		}
	}
	climbdown
	{
		default
		{
			both climb_down
		}
	}
	idleprone
	{
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			legs prone_legs torso mortar_deployed
		}
		weapons Mortar AND Granatwerfer
		{
			legs prone_legs torso e_prone_mortar_stand
		}
		weapons Satchel Charge
		{
			legs prone_legs torso prone_grenade_idle
		}
		weapons satchel charge detonator
		{
			legs prone_legs torso prone_poke_idle
		}
		weapons medicheal
		{
			legs prone_legs torso prone_poke_idle
		}
		weapons Mobile MG 42 Bipod AND Mobile Browning Bipod
		{
			legs prone_legs torso prone_mg42_idle
		}
		weapons Mobile MG 42 AND Mobile Browning
		{
			legs prone_legs torso prone_mg42_idle
		}
		weapons bazooka
		{
			legs prone_legs torso e_prone_rifle_snipeidle
		}
		weapons panzerfaust
		{
			legs prone_legs torso prone_panzor_idle
		}
		weapons machineguns
		{
			legs prone_legs torso prone_mg_idle
		}
		weapons binoculars
		{
			legs prone_legs torso e_prone_binocs_idle
		}
		weapons binoculars, gen_bitflag zooming
		{
			legs prone_legs torso e_prone_binocs_lie
		}
		weapons smokeGrenade
		{
			legs prone_legs torso prone_grenade_idle
		}
		weapons Ammo Pack
		{
			legs prone_legs torso prone_grenade_idle
		}
		weapons Landmine
		{
			legs prone_legs torso prone_grenade_idle
		}
		weapons medicheal
		{
			legs prone_legs torso prone_poke_idle
		}
		weapons special
		{
			legs prone_legs torso prone_poke_idle
		}
		weapons Syringe AND Adrenaline Syringe
		{
			legs prone_legs torso prone_poke_idle
		}
		weapons throwables, gen_bitflag holding
		{
			legs prone_legs torso holding_grenadeA
			legs prone_legs torso holding_grenadeB
		}
		weapons throwables AND throwables_underhand
		{
			legs prone_legs torso prone_grenade_idle
		}
		weapons knives
		{
			legs prone_legs torso prone_knife_attack
		}
		weapons pistols
		{
			legs prone_legs torso prone_pistol_idle
		}
		weapons akimbo_pistols
		{
			legs prone_legs torso e_prone_pistols_idle	// FIXME
		}
		weapons Scoped M1 Garand
		{
			legs prone_legs torso prone_rifle_idle
		}
		weapons FG 42 Paratroop Rifle
		{
			legs prone_legs torso prone_rifle_idle
		}
		weapons K43 Rifle
		{
			legs prone_legs torso prone_rifle_idle
		}
		weapons gpg40
		{
			legs prone_legs torso e_prone_rifle_altidle
		}
		weapons M7
		{
			legs prone_legs torso e_prone_rifle_altidle
		}
		weapons m1 garand
		{
			legs prone_legs torso prone_rifle_idle
		}
		weapons Scoped K43 Rifle
		{
			legs prone_legs torso prone_rifle_idle
		}
		weapons K43 Rifle Scope
		{
			legs prone_legs torso e_prone_rifle_snipeidle
		}
		weapons M1 Garand Scope
		{
			legs prone_legs torso e_prone_rifle_snipeidle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs prone_legs torso e_prone_rifle_snipeidle
		}
		weapons rifles
		{
			legs prone_legs torso prone_rifle_idle
		}
		default
		{
			legs prone_legs torso Prone_Pistol_idle
		}
	}
	prone
	{
		default
		{
			both prone_crawl
		}
	}
	pronebk
	{
		default
		{
			both prone_crawl_bk
		}
	}

	turnright
	{
		// - fixed movetype condition, so reenabled crouch
		// - nixing 'weapons machineguns' because we don't
		// want to just slide with any weapon; adding mounted MG42
		// so that we don't dance around in the tank
		movetype idlecr, NOT mounted MG42
		{
			legs turn_crch_R
		}
		movetype idle, NOT mounted MG42
		{
			legs turn_machinegun_R
		}

	}
	turnleft
	{
		// - fixed movetype condition, so reenabled crouch
		// - nixing 'weapons machineguns' because we don't
		// want to just slide with any weapon
		movetype idlecr, NOT mounted MG42
		{
			legs turn_crch_L
		}
		movetype idle, NOT mounted MG42
		{
			legs turn_machinegun_R
		}
	}

	fallen
	{
		default
		{
			both wounded_idle_1
		}
	}

	radio
	{
		default
		{
			both stand_radio
		}
	}
	radiocr
	{
		default
		{
			torso stand_radio legs alert_crchidle_1h 
		}
	}
	radioprone
	{
		default
		{
			legs prone_legs torso prone_poke_idle
		}
	}
}

//==========================================================================
// EVENTS
//
// format:
//
// <event description>
// {
//		[DEFAULT / <condition type> [<condition value>], ...]
//		{
//			<both/legs/torso> <animation> [sound <filename>]
//			<both/legs/torso> <animation> [sound <filename>]
//			...
//		}
// }
//
// legend:
//
// <event description>: death, pain, fireweapon, jump, jumpbk, land, dropweapon,
//		raiseweapon, climbdismount, reload
//
//	NOTE: for gameplay anims (weapons firing, reload, etc) that show no legs movement
//		only the torso should animation from here, leave the legs doing what their
//		locomotive anims want them to do
//

EVENTS

fireweapon
{
// ADRENALINE SYRINGE
	weapons Adrenaline Syringe, movetype walk AND turnleft AND turnright AND idlecr AND idle AND crouching AND run AND swim AND backstep AND swimbk
	{
		torso self_inject
	}
// Mortar
	weapons Mounted Mortar AND Mounted Granatwerfer
	{
		torso mortar_fire
	}
// SATCHEL CHARGE
	weapons Satchel Charge
	{
		torso throw_underhand
	}
// SATCHEL CHARGE DETONATOR
	weapons Satchel Charge Detonator
	{
		torso satchel_remote_fire
	}
// MG 42
	mounted MG42
	{
		both firing_mg42
	}
// smokeGrenade
	// - support overhand throws for airstrike tags
	weapons smokeGrenade, underhand
	{
		torso firing_grenadeB
	}
	weapons smokeGrenade
	{
		torso firing_grenadeA
	}
// MEDICHEAL, AMMOPACK, LANDMINE
	weapons medicheal AND Ammo Pack AND Landmine
	{
		torso throw_underhand
	}
// SPECIAL
	weapons special
	{
		torso firing_pliers
	}
// SYRINGE
	weapons Syringe, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_syringe
	}
	weapons Syringe, movetype crouching
	{
		torso firing_syringe
	}
	weapons Syringe, movetype run AND swim
	{
		torso firing_syringe
	}
	weapons Syringe, movetype backstep AND swimbk
	{
		torso firing_syringe
	}
	weapons Syringe
	{
		torso firing_syringe
	}
// BAZOOKA
	weapons bazooka
	{
		torso stand_rifle
	}
// PANZERFAUST
	weapons panzerfaust, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_panzer
	}
	weapons panzerfaust, movetype crouching
	{
		torso firing_panzer
	}
	weapons panzerfaust, movetype run AND swim
	{
		torso firing_panzer
	}
	weapons panzerfaust, movetype backstep AND swimbk
	{
		torso firing_panzer
	}
	weapons panzerfaust
	{
		torso firing_panzer
	}
// GRENADES
	// support overhand throws for grenades
	weapons throwables, underhand
	{
		torso firing_grenadeB
	}
	weapons throwables
	{
		torso firing_grenadeA
	}
	// only dynamite is still handled here, always underhand
	weapons throwables_underhand, movetype idle
	{
		torso throw_underhand
	}
	weapons throwables_underhand, movetype run AND walk AND straferight AND strafeleft AND backstep AND turnleft AND turnright AND idlecr
	{
		torso throw_underhand
	}

// KNIVES
	weapons knives
	{
		torso firing_knifeA
	}
// PISTOLS
	weapons pistols, movetype straferight
	{
		torso firing_pistolB_1
	}
	weapons pistols, movetype strafeleft
	{
		torso firing_pistolB_1
	}
	weapons pistols, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_pistolB_1
		torso firing_pistolB_2
	}
	weapons pistols, movetype walkcrbk
	{
		torso firing_crbk_1h
	}
	weapons pistols, movetype crouching
	{
		torso firing_crch_1h
	}
	weapons pistols, movetype run AND swim
	{
		torso firing_pistolB_1
	}
	weapons pistols, movetype backstep AND swimbk
	{
		torso firing_pistolB_1
	}
	weapons pistols
	{
		torso firing_pistolB_1
		torso firing_pistolB_2
	}
// AKIMBO PISTOLS
	weapons akimbo_pistols, movetype straferight
	{
		torso firing_akimbo
	}
	weapons akimbo_pistols, movetype strafeleft
	{
		torso firing_akimbo
	}
	weapons akimbo_pistols, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_akimbo
	}
	weapons akimbo_pistols, movetype walkcrbk
	{
		torso firing_akimbo	// FIXME
	}
	weapons akimbo_pistols, movetype crouching
	{
		torso firing_akimbo	// FIXME
	}
	weapons akimbo_pistols, movetype run AND swim
	{
		torso firing_akimbo
	}
	weapons akimbo_pistols, movetype backstep AND swimbk
	{
		torso firing_akimbo
	}
	weapons akimbo_pistols
	{
		torso firing_akimbo
	}
// MOBILE MG 42
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso firing_mobilemg42
	}
	weapons Mobile MG 42 AND Mobile Browning, movetype straferight
	{
		torso alert_run_2h duration 50
	}
	weapons Mobile MG 42 AND Mobile Browning, movetype strafeleft
	{
		torso alert_run_2h duration 50
	}
	weapons Mobile MG 42 AND Mobile Browning, movetype walk AND turnleft AND turnright AND idlecr
	{
		torso firing_mobilemg42 duration 50
	}
	weapons Mobile MG 42 AND Mobile Browning, movetype walkcrbk
	{
		torso firing_crbk_2h duration 50
	}
	weapons Mobile MG 42 AND Mobile Browning, movetype crouching
	{
		torso firing_crch_2h duration 50
	}
	weapons Mobile MG 42 AND Mobile Browning, movetype run AND swim
	{
		torso alert_run_2h duration 50
	}
	weapons Mobile MG 42 AND Mobile Browning, movetype backstep AND swimbk
	{
		torso alert_bk_2h duration 50
	}
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso firing_mobilemg42 duration 50
	}
// MACHINEGUNS
	weapons machineguns, movetype straferight
	{
		torso alert_run_2h duration 50
	}
	weapons machineguns, movetype strafeleft
	{
		torso alert_run_2h duration 50
	}
	weapons machineguns, movetype walk AND turnleft AND turnright AND idlecr
	{
		torso firing_machinegun duration 50
	}
	weapons machineguns, movetype walkcrbk
	{
		torso firing_crbk_2h duration 50
	}
	weapons machineguns, movetype crouching
	{
		torso firing_crch_2h duration 50
	}
	weapons machineguns, movetype run AND swim
	{
		torso alert_run_2h duration 50
	}
	weapons machineguns, movetype backstep AND swimbk
	{
		torso alert_bk_2h duration 50
	}
	weapons machineguns
	{
		torso firing_machinegun duration 50
	}
// RIFLES
	weapons Scoped M1 Garand, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_srifle
	}
	weapons Scoped M1 Garand, movetype crouching
	{
		torso firing_crch_srifle
	}
	weapons Scoped M1 Garand, movetype run AND swim
	{
		torso firing_run_srifle
	}
	weapons Scoped M1 Garand, movetype backstep AND swimbk
	{
		torso firing_bk_srifle
	}
	weapons Scoped M1 Garand
	{
		torso firing_srifle
	}
	weapons FG 42 Paratroop Rifle, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_srifle
	}
	weapons FG 42 Paratroop Rifle, movetype crouching
	{
		torso firing_crch_srifle
	}
	weapons FG 42 Paratroop Rifle, movetype run AND swim
	{
		torso firing_run_srifle
	}
	weapons FG 42 Paratroop Rifle, movetype backstep AND swimbk
	{
		torso firing_bk_srifle
	}
	weapons FG 42 Paratroop Rifle
	{
		torso firing_srifle
	}
	weapons K43 Rifle, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_srifle
	}
	weapons K43 Rifle, movetype crouching
	{
		torso firing_crch_srifle
	}
	weapons K43 Rifle, movetype run AND swim
	{
		torso firing_run_srifle
	}
	weapons K43 Rifle, movetype backstep AND swimbk
	{
		torso firing_bk_srifle
	}
	weapons K43 Rifle
	{
		torso firing_srifle
	}
	weapons gpg40, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_grenlauncher
	}
	weapons gpg40, movetype crouching
	{
		torso firing_grenlauncher
	}
	weapons gpg40, movetype run AND swim
	{
		torso firing_grenlauncher
	}
	weapons gpg40, movetype backstep AND swimbk
	{
		torso firing_grenlauncher
	}
	weapons gpg40
	{
		torso firing_grenlauncher
	}
	weapons M7, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_grenlauncher
	}
	weapons M7, movetype crouching
	{
		torso firing_grenlauncher
	}
	weapons M7, movetype run AND swim
	{
		torso firing_grenlauncher
	}
	weapons M7, movetype backstep AND swimbk
	{
		torso firing_grenlauncher
	}
	weapons M7
	{
		torso firing_grenlauncher
	}
	weapons m1 garand, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_srifle
	}
	weapons m1 garand, movetype crouching
	{
		torso firing_crch_srifle
	}
	weapons m1 garand, movetype run AND swim
	{
		torso firing_run_srifle
	}
	weapons m1 garand, movetype backstep AND swimbk
	{
		torso firing_bk_srifle
	}
	weapons m1 garand
	{
		torso firing_srifle
	}
	weapons FG 42 Paratroop Rifle Scope, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_rifle
	}
	weapons FG 42 Paratroop Rifle Scope, movetype crouching
	{
		torso firing_crch_2h
	}
	weapons FG 42 Paratroop Rifle Scope, movetype run AND swim
	{
		torso alert_run_2h
	}
	weapons FG 42 Paratroop Rifle Scope, movetype backstep AND swimbk
	{
		torso firing_bk_2h
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		torso firing_rifle
	}
	weapons Scoped K43 Rifle, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_srifle
	}
	weapons Scoped K43 Rifle, movetype crouching
	{
		torso firing_crch_srifle
	}
	weapons Scoped K43 Rifle, movetype run AND swim
	{
		torso firing_run_srifle
	}
	weapons Scoped K43 Rifle, movetype backstep AND swimbk
	{
		torso firing_bk_srifle
	}
	weapons Scoped K43 Rifle
	{
		torso firing_srifle
	}
	weapons K43 Rifle Scope, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_rifle
	}
	weapons K43 Rifle Scope, movetype crouching
	{
		torso firing_crch_2h
	}
	weapons K43 Rifle Scope, movetype run AND swim
	{
		torso alert_run_2h
	}
	weapons K43 Rifle Scope, movetype backstep AND swimbk
	{
		torso firing_bk_2h
	}
	weapons K43 Rifle Scope
	{
		torso firing_rifle
	}
	weapons M1 Garand Scope, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_rifle
	}
	weapons M1 Garand Scope, movetype crouching
	{
		torso firing_crch_2h
	}
	weapons M1 Garand Scope, movetype run AND swim
	{
		torso alert_run_2h
	}
	weapons M1 Garand Scope, movetype backstep AND swimbk
	{
		torso firing_bk_2h
	}
	weapons M1 Garand Scope
	{
		torso firing_rifle
	}
}

//zoomin
//{
//	weapons binoculars
//	{
//		torso raise_binoculars
//	}
//}

fireweapon2
{
// AKIMBO PISTOLS
	weapons akimbo_pistols, movetype straferight
	{
		torso firing_akimbo2
	}
	weapons akimbo_pistols, movetype strafeleft
	{
		torso firing_akimbo2
	}
	weapons akimbo_pistols, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_akimbo2
	}
	weapons akimbo_pistols, movetype walkcrbk
	{
		torso firing_akimbo2	// FIXME
	}
	weapons akimbo_pistols, movetype crouching
	{
		torso firing_akimbo2	// FIXME
	}
	weapons akimbo_pistols, movetype run AND swim
	{
		torso firing_akimbo2
	}
	weapons akimbo_pistols, movetype backstep AND swimbk
	{
		torso firing_akimbo2
	}
	weapons akimbo_pistols
	{
		torso firing_akimbo2
	}
}

fireweaponprone
{
	weapons satchel charge
	{
		torso prone_grenade_fire
	}
	weapons satchel charge detonator
	{
		torso prone_poke_fire
	}
	weapons smokeGrenade
	{
		torso prone_grenade_fire
	}
	weapons Ammo Pack
	{
		torso prone_grenade_fire
	}
	weapons Landmine
	{
		torso prone_grenade_fire
	}
	weapons Satchel Charge
	{
		torso prone_grenade_fire
	}
	weapons medicheal
	{
		torso prone_poke_fire
	}
	weapons special
	{
		torso prone_poke_fire
	}
	weapons Syringe AND Adrenaline Syringe
	{
		torso prone_poke_fire
	}
	weapons bazooka
	{
		torso e_prone_rifle_snipefire
	}
	weapons panzerfaust
	{
		torso prone_panzor_idle
	}
	weapons throwables AND throwables_underhand
	{
		torso prone_grenade_fire
	}
	weapons knives
	{
		torso prone_knife_attack
	}
	weapons pistols
	{
		torso prone_pistol_fire
	}
	weapons akimbo_pistols	// FIXedME
	{
		torso e_prone_pistols_fire
	}
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso prone_mg42_fire
	}
	weapons Mobile MG 42 Bipod  AND Mobile Browning Bipod
	{
		torso prone_mg42_fire
	}
	weapons machineguns
	{
		torso prone_mg_fire
	}
	weapons Scoped M1 Garand
	{
		torso prone_rifle_fire
	}
	weapons FG 42 Paratroop Rifle
	{
		torso prone_rifle_fire
	}
	weapons K43 Rifle
	{
		torso prone_rifle_fire
	}
	weapons gpg40
	{
		torso e_prone_rifle_fire
	}
	weapons M7
	{
		torso e_prone_rifle_fire
	}
	weapons m1 garand
	{
		torso prone_rifle_fire
	}
	weapons Scoped K43 Rifle
	{
		torso prone_rifle_fire
	}
	weapons K43 Rifle Scope
	{
		torso e_prone_rifle_snipefire
	}
	weapons M1 Garand Scope
	{
		torso e_prone_rifle_snipefire
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		torso e_prone_rifle_snipefire
	}
}

fireweapon2prone
{
	weapons akimbo_pistols
	{
		torso e_prone_pistols_fire2
	}
}

raiseweaponprone
{
	weapons Mortar AND Granatwerfer
	{
		torso e_prone_mortar_raise
	}
	weapons binoculars
	{
		torso e_prone_binocs_rase
	}
	weapons satchel charge
	{
		torso prone_grenade_switch
	}
	weapons satchel charge detonator
	{
		torso prone_poke_switch
	}
	weapons smokeGrenade
	{
		torso prone_grenade_switch
	}
	weapons Ammo Pack
	{
		torso prone_grenade_switch
	}
	weapons Landmine
	{
		torso prone_grenade_switch
	}
	weapons Satchel Charge
	{
		torso prone_grenade_switch
	}
	weapons medicheal
	{
		torso prone_poke_switch
	}
	weapons special
	{
		torso prone_poke_switch
	}
	weapons Syringe AND Adrenaline Syringe
	{
		torso prone_poke_switch
	}
	weapons bazooka
	{
		torso prone_rifle_switch
	}
	weapons panzerfaust
	{
		torso prone_panzor_switch
	}
	weapons throwables AND throwables_underhand
	{
		torso prone_grenade_switch
	}
	weapons knives
	{
		torso prone_knife_switch
	}
	weapons pistols
	{
		torso e_prone_pistol_switch
	}
	weapons akimbo_pistols	// FIXedME
	{
		torso e_prone_pistols_switch
	}
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso prone_mg42_switch
	}
	weapons machineguns
	{
		torso prone_mg_switch
	}
	weapons Scoped M1 Garand
	{
		torso prone_rifle_switch
	}
	weapons FG 42 Paratroop Rifle
	{
		torso prone_rifle_switch
	}
	weapons K43 Rifle
	{
		torso prone_rifle_switch
	}
	weapons gpg40
	{
		torso e_prone_rifle_altfire
	}
	weapons M7
	{
		torso e_prone_rifle_altfire
	}
	weapons m1 garand
	{
		torso prone_rifle_switch
	}
	weapons Scoped K43 Rifle
	{
		torso prone_rifle_switch
	}
	weapons K43 Rifle Scope
	{
		torso e_prone_rifle_snipe
	}
	weapons M1 Garand Scope
	{
		torso e_prone_rifle_snipe
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		torso e_prone_rifle_snipe
	}
}

reloadprone
{
	weapons smokeGrenade
	{
		torso prone_grenade_switch
	}
	weapons Ammo Pack
	{
		torso prone_grenade_switch
	}
	weapons Landmine
	{
		torso prone_grenade_switch
	}
	weapons Satchel Charge
	{
		torso prone_grenade_switch
	}
	weapons medicheal
	{
		torso prone_poke_switch
	}
	weapons special
	{
		torso prone_poke_switch
	}
	weapons Syringe AND Adrenaline Syringe
	{
		torso prone_poke_switch
	}
	weapons throwables AND throwables_underhand
	{
		torso prone_grenade_switch
	}
	weapons pistols
	{
		torso prone_pistol_reload
	}
	weapons akimbo_pistols
	{
		torso e_prone_pistols_reload
	}
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso prone_mg42_reload
	}
	weapons Mobile MG 42 Bipod  AND Mobile Browning Bipod
	{
		torso prone_mg42_reload
	}
	weapons machineguns
	{
		torso prone_mg_reload
	}
	weapons Scoped M1 Garand
	{
		torso prone_rifle_reload
	}
	weapons FG 42 Paratroop Rifle
	{
		torso prone_rifle_reload
	}
	weapons K43 Rifle
	{
		torso prone_rifle_reload
	}
	weapons gpg40
	{
		torso e_prone_rifle_attach
	}
	weapons M7
	{
		torso e_prone_rifle_attach
	}
	weapons m1 garand
	{
		torso prone_rifle_reload
	}
	weapons Scoped K43 Rifle
	{
		torso prone_rifle_reload
	}
	weapons K43 Rifle Scope
	{
		torso prone_rifle_reload
	}
	weapons M1 Garand Scope
	{
		torso prone_rifle_reload
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		torso prone_rifle_reload
	}
}

raiseweapon
{
	weapons Mortar AND Granatwerfer
	{
		torso e_mortar_raise
	}
	weapons satchel charge
	{
		torso raise_medpack
	}
	weapons satchel charge detonator
	{
		torso satchel_remote_raise
	}
	weapons smokeGrenade AND binoculars
	{
		torso raise_grenade
	}
	weapons Syringe AND Adrenaline Syringe
	{
		torso raise_knife
	}
	weapons Ammo Pack
	{
		torso raise_medpack
	}
	weapons Landmine
	{
		torso raise_grenade
	}
	weapons Satchel Charge
	{
		torso raise_medpack
	}
	weapons medicheal
	{
		torso raise_medpack
	}
	weapons special
	{
		torso raise_knife
	}
	weapons bazooka
	{
		torso raise_machinegun
	}
	weapons panzerfaust
	{
		torso raise_panzer
	}
	weapons knives
	{
		torso raise_knife
	}
	weapons pistols
	{
		torso raise_pistolA
	}
	weapons akimbo_pistols
	{
		torso raise_akimbo
	}
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso raise_mobilemg42
	}
	weapons machineguns
	{
		torso raise_machinegun
	}
	weapons Scoped M1 Garand
	{
		torso raise_machinegun
	}
	weapons FG 42 Paratroop Rifle
	{
		torso raise_machinegun
	}
	weapons K43 Rifle
	{
		torso raise_machinegun
	}
	weapons gpg40
	{
		torso raise_grenlauncher
	}
	weapons M7
	{
		torso raise_grenlauncher
	}
	weapons m1 garand
	{
		torso raise_machinegun
	}
	weapons Scoped K43 Rifle
	{
		torso raise_machinegun
	}
	weapons K43 Rifle Scope
	{
		torso raise_sniper
	}
	weapons M1 Garand Scope
	{
		torso raise_sniper
	}
	weapons throwables AND throwables_underhand
	{
		torso raise_grenade
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		torso raise_sniper
	}
}

reload
{
	weapons satchel charge
	{
		torso raise_medpack
	}
	/*weapons Mortar AND Granatwerfer
	{
		torso mortar_reload
	}*/
	weapons smokeGrenade
	{
		torso raise_grenade
	}
	weapons Syringe AND Adrenaline Syringe
	{
		torso raise_knife
	}
	weapons Ammo Pack
	{
		torso raise_medpack
	}
	weapons Landmine
	{
		torso raise_grenade
	}
	weapons Satchel Charge
	{
		torso raise_medpack
	}
	weapons medicheal
	{
		torso raise_medpack
	}
	weapons special
	{
		torso raise_knife
	}
	weapons bazooka
	{
		torso reload_rifle
	}
	weapons panzerfaust
	{
		torso reload_panzer
	}
	weapons pistols, movetype idlecr
	{
		torso reload_pistol_cr
	}
	weapons pistols
	{
		torso reload_pistol
	}
	weapons akimbo_pistols, movetype idlecr
	{
		torso reload_akimbo	// FIXed you!
	}
	weapons akimbo_pistols
	{
		torso reload_akimbo
	}
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso reload_mobilemg42
	}
	weapons machineguns, movetype idlecr
	{
		torso reload_machinegun_cr
	}
	weapons machineguns
	{
		torso reload_machinegun
	}
	weapons Scoped M1 Garand
	{
		torso reload_machinegun
	}
	weapons FG 42 Paratroop Rifle
	{
		torso reload_machinegun
	}
	weapons K43 Rifle
	{
		torso reload_machinegun
	}
	weapons gpg40
	{
		torso reload_grenlauncher
	}
	weapons M7
	{
		torso reload_grenlauncher
	}
	weapons m1 garand
	{
		torso reload_machinegun
	}
	weapons Scoped K43 Rifle
	{
		torso reload_machinegun
	}
	weapons K43 Rifle Scope
	{
		torso reload_rifle
	}
	weapons M1 Garand Scope
	{
		torso reload_rifle
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		torso reload_rifle
	}
}

jump
{
	weapons none, movetype run
	{
		both jump_1step_1h
	}
	weapons none
	{
		both jump_nostep_1h
	}
	weapons one_handed_weapons, movetype run
	{
		both jump_1step_1h
	}
	weapons one_handed_weapons
	{
		both jump_nostep_1h
	}
//	weapons rifles, movetype run
//	{
//		legs jump_1step_2h torso stand_rifle
//	}
//	weapons rifles
//	{
//		legs jump_nostep_1h torso stand_rifle
//	}
	weapons Scoped M1 Garand, movetype run
	{
		legs jump_1step_2h
	}
	weapons Scoped M1 Garand
	{
		legs jump_nostep_1h
	}
	weapons FG 42 Paratroop Rifle, movetype run
	{
		legs jump_1step_2h
	}
	weapons FG 42 Paratroop Rifle
	{
		legs jump_nostep_1h
	}
	weapons K43 Rifle, movetype run
	{
		legs jump_1step_2h
	}
	weapons K43 Rifle
	{
		legs jump_nostep_1h
	}
	weapons gpg40, movetype run
	{
		legs jump_1step_2h
	}
	weapons gpg40
	{
		legs jump_nostep_1h
	}
	weapons M7, movetype run
	{
		legs jump_1step_2h
	}
	weapons M7
	{
		legs jump_nostep_1h
	}
	weapons m1 garand, movetype run
	{
		legs jump_1step_2h
	}
	weapons m1 garand
	{
		legs jump_nostep_1h
	}
	weapons Scoped K43 Rifle, movetype run
	{
		legs jump_1step_2h
	}
	weapons Scoped K43 Rifle
	{
		legs jump_nostep_1h
	}
	weapons K43 Rifle Scope, movetype run
	{
		legs jump_1step_2h torso stand_rifle
	}
	weapons K43 Rifle Scope
	{
		legs jump_nostep_1h torso stand_rifle
	}
	weapons M1 Garand Scope, movetype run
	{
		legs jump_1step_2h torso stand_rifle
	}
	weapons M1 Garand Scope
	{
		legs jump_nostep_1h torso stand_rifle
	}
	weapons FG 42 Paratroop Rifle Scope, movetype run
	{
		legs jump_1step_2h torso stand_rifle
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		legs jump_nostep_1h torso stand_rifle
	}
	weapons bazooka, movetype run
	{
		legs jump_1step_2h torso stand_rifle
	}
	weapons bazooka
	{
		legs jump_nostep_1h torso stand_rifle
	}
	weapons panzerfaust, movetype run
	{
		legs jump_1step_2h torso stand_panzer
	}
	weapons panzerfaust
	{
		legs jump_nostep_1h torso stand_panzer
	}
	weapons two_handed_weapons, movetype run
	{
		both jump_1step_2h
	}
	weapons two_handed_weapons
	{
		both jump_nostep_1h
	}
	default
	{
		both jump_1step_1h
	}
}

jumpbk
{
	weapons one_handed_weapons, movetype run
	{
		both jump_1step_1h
	}
	weapons one_handed_weapons
	{
		both jump_nostep_1h
	}
//	weapons rifles, movetype run
//	{
//		legs jump_1step_2h torso stand_rifle
//	}
//	weapons rifles
//	{
//		legs jump_nostep_1h torso stand_rifle
//	}
	weapons Scoped M1 Garand, movetype run
	{
		legs jump_1step_2h
	}
	weapons Scoped M1 Garand
	{
		legs jump_nostep_1h
	}
	weapons FG 42 Paratroop Rifle, movetype run
	{
		legs jump_1step_2h
	}
	weapons FG 42 Paratroop Rifle
	{
		legs jump_nostep_1h
	}
	weapons K43 Rifle, movetype run
	{
		legs jump_1step_2h
	}
	weapons K43 Rifle
	{
		legs jump_nostep_1h
	}
	weapons gpg40, movetype run
	{
		legs jump_1step_2h
	}
	weapons gpg40
	{
		legs jump_nostep_1h
	}
	weapons M7, movetype run
	{
		legs jump_1step_2h
	}
	weapons M7
	{
		legs jump_nostep_1h
	}
	weapons m1 garand, movetype run
	{
		legs jump_1step_2h
	}
	weapons m1 garand
	{
		legs jump_nostep_1h
	}
	weapons Scoped K43 Rifle, movetype run
	{
		legs jump_1step_2h
	}
	weapons Scoped K43 Rifle
	{
		legs jump_nostep_1h
	}
	weapons K43 Rifle Scope, movetype run
	{
		legs jump_1step_2h torso stand_rifle
	}
	weapons K43 Rifle Scope
	{
		legs jump_nostep_1h torso stand_rifle
	}
	weapons M1 Garand Scope, movetype run
	{
		legs jump_1step_2h torso stand_rifle
	}
	weapons M1 Garand Scope
	{
		legs jump_nostep_1h torso stand_rifle
	}
	weapons FG 42 Paratroop Rifle Scope, movetype run
	{
		legs jump_1step_2h torso stand_rifle
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		legs jump_nostep_1h torso stand_rifle
	}
	weapons bazooka, movetype run
	{
		legs jump_1step_2h torso stand_rifle
	}
	weapons bazooka
	{
		legs jump_nostep_1h torso stand_rifle
	}
	weapons panzerfaust, movetype run
	{
		legs jump_1step_2h torso stand_panzer
	}
	weapons panzerfaust
	{
		legs jump_nostep_1h torso stand_panzer
	}
	weapons two_handed_weapons, movetype run
	{
		both jump_1step_2h
	}
	weapons two_handed_weapons
	{
		both jump_nostep_1h
	}
	default
	{
		both jump_1step_1h
	}
}

climbmount
{
	default
	{
		both climb_start
	}
}

climbdismount
{
	default
	{
		both climb_dis
	}
}

DEATH
{
	suicide
	{
		both death_rifle_head_2
	}

	enemy_weapon knives, enemy_position behind
	{
		both death_machinegun_1
		both death_machinegun_2
		both death_gut
	}

	enemy_weapon machineguns
	{
		both death_machinegun_1
		both death_machinegun_2
		both death_gut
	}

	enemy_weapon rifles, impact_point head
	{
		both death_machinegun_1
		both death_machinegun_2
		both death_gut
	}

	enemy_weapon rifles, impact_point chest
	{
		both death_machinegun_1
		both death_machinegun_2
		both death_gut
	}
	enemy_weapon flamethrower
	{
		both death_machinegun_1
		both death_machinegun_2
		both death_gut
	}

	default
	{
		both death_machinegun_1
		both death_machinegun_2
		both death_gut
	}
}

revive
{
	default
	{
		both revive
	}
}

nopower
{
	default
	{
		torso e_no_juice
	}
}

pain
{
	movetype fallen
	{
		legs wounded_idle_1
	}
	movetype proning
	{
		legs prone_legs
	}
	movetype swimbk AND swim
	{
		legs e_swim_1h
	}
	movetype crouching, impact_point head
	{
		torso pain_cr_head
	}
	movetype crouching, impact_point shoulder_right
	{
		torso pain_cr_shoulderR
	}
	movetype crouching, impact_point shoulder_left
	{
		torso pain_cr_shoulderL
	}
	movetype crouching	// pick one at random if they failed
	{
		torso pain_cr_head
		torso pain_cr_shoulderR
		torso pain_cr_shoulderL
	}
	enemy_weapon flamethrower
	{
		torso pain_fire
	}
	stunned
	{
		torso pain_daze
	}
	impact_point head
	{
		torso pain_head
	}
	impact_point chest
	{
		torso pain_chest
	}
	impact_point gut
	{
		torso pain_gut
	}
	impact_point groin
	{
		torso pain_groin
	}
	impact_point shoulder_right
	{
		torso pain_shoulderR
	}
	impact_point shoulder_left
	{
		torso pain_shoulderL
	}
	impact_point knee_right
	{
	// legs ?
		torso pain_kneeR
	}
	impact_point knee_left
	{
	// legs ?
		torso pain_kneeL
	}
	default
	{
		torso pain_chest
		torso pain_gut
		torso pain_groin
	}
}

do_alt_weapon_mode
{
	weapons K43 Rifle
	{
		torso reload_grenlauncher
	}
	weapons m1 garand
	{
		torso reload_grenlauncher
	}
	weapons gpg40
	{
		torso reload_grenlauncher
	}
	weapons M7
	{
		torso reload_grenlauncher
	}
	weapons Luger
	{
		torso attach_silencer
	}
	weapons Colt
	{
		torso attach_silencer
	}
	weapons Silenced Luger
	{
		torso attach_silencer
	}
	weapons Silenced Colt
	{
		torso attach_silencer
	}
}

undo_alt_weapon_mode
{
	weapons K43 Rifle
	{
		torso detach_grenlauncher
	}
	weapons m1 garand
	{
		torso detach_grenlauncher
	}
	weapons gpg40
	{
		torso detach_grenlauncher
	}
	weapons M7
	{
		torso detach_grenlauncher
	}
	weapons Luger
	{
		torso detach_silencer
	}
	weapons Colt
	{
		torso detach_silencer
	}
	weapons Silenced Luger
	{
		torso detach_silencer
	}
	weapons Silenced Colt
	{
		torso detach_silencer
	}
}

do_alt_weapon_mode_prone
{
	weapons K43 Rifle
	{
		torso e_prone_rifle_attach
	}
	weapons m1 garand
	{
		torso e_prone_rifle_attach
	}
	weapons gpg40
	{
		torso e_prone_rifle_attach
	}
	weapons M7
	{
		torso e_prone_rifle_attach
	}
	weapons Luger
	{
		torso e_prone_pistol_attach
	}
	weapons Colt
	{
		torso e_prone_pistol_attach
	}
	weapons Silenced Luger
	{
		torso e_prone_pistol_attach
	}
	weapons Silenced Colt
	{
		torso e_prone_pistol_attach
	}
}

undo_alt_weapon_mode_prone
{
	weapons K43 Rifle
	{
		torso e_prone_rifle_detach
	}
	weapons m1 garand
	{
		torso e_prone_rifle_detach
	}
	weapons gpg40
	{
		torso e_prone_rifle_detach
	}
	weapons M7
	{
		torso e_prone_rifle_detach
	}
	weapons Luger
	{
		torso e_prone_pistol_detach
	}
	weapons Colt
	{
		torso e_prone_pistol_detach
	}
	weapons Silenced Luger
	{
		torso e_prone_pistol_detach
	}
	weapons Silenced Colt
	{
		torso e_prone_pistol_detach
	}
}

//==========================================================================
// CANNED_ANIMATIONS
//
//	These animations are played at random, momentarily cutting off the
//	above "normal" animations.
//
//	format:
//
//	(see ANIMATION section above)
//
//canned_animations

//==========================================================================
// STATECHANGES
//
// format:
//
// statechange <directionto> <state>
// {
//		[DEFAULT / <condition type> [<condition value>], ...]
//		{
//			<both/legs/torso> <animation> [sound <filename>]
//			<both/legs/torso> <animation> [sound <filename>]
//			...
//		}
// }
//STATECHANGES