.TH etl 1 "9 January 2013" "" "ET: Legacy client and listen server man page"

.SH NAME
etl \- ET: Legacy client and listen server 

..SH SYNOPSIS
.B etl
.RI [ options ]
.br

.SH DESCRIPTION
\fBetl\fP (ET: Legacy) is an open source game based on the code of Wolfenstein: Enemy Territory which was released under the GPLv3 license. The main goal of this project is to fix bugs, remove old dependencies and make it playable on all major operating systems while still remaining compatible with the ET 2.60b version and as many of its mods as possible. Let's keep ET alive!

.SH OPTIONS

.IP \fB\-v,--version\fP
Prints version info

.IP \fB\+\fP
Passes commands into the game. Syntax is +<command> <param> <value>. F.e. '+set g_warmup 30' or '+exec etl_server.cfg'. Use space between more than one command.

.SH NOTES

We do appreciate any contribution to the project such as patches, suggestions or comments.
For any issues visit http://www.etlegacy.com or mail to mail@etlegacy.com

.SH "SEE ALSO"

etlded - The dedicated server of ET: Legacy 

.SH BUGS

To report a bug, please visit http://www.etlegacy.com/projects/etlegacy/issues/

.SH AUTHORS

ET:Legacy project team

.SH COPYRIGHT

ET:Legacy is distributed under the GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007 