.TH etlded 6 "9 January 2013" "" "ET: Legacy server man page"

.SH NAME
etlded \- ET: Legacy dedicated server

.SH SYNOPSIS
.B etlded
.RI [ options ]
.br

.SH DESCRIPTION
\fBetlded\fP (ET: Legacy) is an open source project based on the code of Wolfenstein: Enemy Territory, which was released in 2010 under the terms of GPLv3.

.SH OPTIONS

.IP \fB\-v,--version\fP
Prints version info

.IP \fB\+\fP
Passes commands into the game. Syntax is +<command> <param> <value>. F.e. '+set g_warmup 30' or '+exec etl_server.cfg'. Use space between more than one command.

.SH "SEE ALSO"

etl - The client and listen server of ET: Legacy

.SH BUGS

To report a bug, please visit https://github.com/etlegacy/etlegacy/issues

.SH AUTHORS

ET: Legacy Team - https://www.etlegacy.com

.SH COPYRIGHT

ET: Legacy is distributed under the GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
