.TH etlded  2.71RC1 "9 January 2013" "" "Linux User's Manual"

.SH NAME
etlded \- ET: Legacy dedicated server 

..SH SYNOPSIS
.B etlded
.RI [ options ]
.br

.SH DESCRIPTION
\fBetlded\fP (ET: Legacy) is a game based on the source code of Wolfenstein: Enemy Territory which was released under the GPLv3 license. The main goal of this project is to fix bugs, remove old dependencies and make it playable on all major operating systems while still remaining compatible with the ET 2.60b version and as many of its mods as possible.
Let's keep ET alive!

.SH OPTIONS
.IP \fB\-OPTION\fP
This option...

.SH NOTES

We do appreciate any contribution to the project such as patches, suggestions or comments.
For any issues visit http://www.etlegacy.com or mail to <FIXME>

.SH "SEE ALSO"

etl - The client and listen server of ET: Legacy 

.SH BUGS

To report a bug, please visit http://www.etlegacy.com/projects/etlegacy/issues/

.SH AUTHORS

ET:Legacy project team

.SH COPYRIGHT

ET:Legacy is distributed under the GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007 