add_executable(etlded ${COMMON_SRC} ${MINIZIP_SRC} ${ZLIB_SRC} ${SERVER_SRC} ${PLATFORM_SRC} ${PLATFORM_SERVER_SRC})
target_link_libraries(etlded ${OS_LIBRARIES} ${SERVER_LIBRARIES})
set_target_properties(etlded
	PROPERTIES COMPILE_DEFINITIONS "DEDICATED"
	RUNTIME_OUTPUT_DIRECTORY ""
	RUNTIME_OUTPUT_DIRECTORY_DEBUG ""
	RUNTIME_OUTPUT_DIRECTORY_RELEASE ""
)

if(BUNDLED_CURL)
	add_dependencies(etlded bundled_curl)
endif(BUNDLED_CURL)

install(TARGETS etlded RUNTIME DESTINATION "${INSTALL_DEFAULT_BINDIR}")
