// awf_props.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 3 total shaders

textures/awf_props/tool_m01
{
    qer_editorimage textures/awf_props/tool_m01
	diffuseMap textures/awf_props/tool_m01
	bumpMap textures/awf_props/tool_m01_n
	specularMap textures/awf_props/tool_m01_s
	surfaceparm metalsteps
	implicitMap -
}

textures/awf_props/tool_m06
{
    qer_editorimage textures/awf_props/tool_m06
	diffuseMap textures/awf_props/tool_m06
	bumpMap textures/awf_props/tool_m06_n
	specularMap textures/awf_props/tool_m06_s
	surfaceparm metalsteps
	implicitMap -
}

textures/awf_props/tool_m07
{
    qer_editorimage textures/awf_props/tool_m07
	diffuseMap textures/awf_props/tool_m07
	bumpMap textures/awf_props/tool_m07_n
	specularMap textures/awf_props/tool_m07_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}
