// bunker_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 4 total shaders

textures/bunker_sd/extwall01_sand
{
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap -
}

textures/bunker_sd/extwall02_sand
{
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap -
}

textures/bunker_sd/girder01
{
	surfaceparm metalsteps
	implicitMap -
}

textures/bunker_sd/girder02
{
    qer_editorimage textures/bunker_sd/girder02
	diffusemap textures/bunker_sd/girder02
	specularmap textures/bunker_sd/girder02_s
	bumpmap textures/bunker_sd/girder02_n
	surfaceparm metalsteps
	implicitMap -
}

textures/bunker_sd/girder03
{
    qer_editorimage textures/bunker_sd/girder03
	diffusemap textures/bunker_sd/girder03
	bumpmap textures/bunker_sd/girder03_n
	specularmap textures/bunker_sd/girder03_s
	surfaceparm metalsteps
	implicitMap -
}

textures/bunker_sd/tinroof01
{
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap -
}

textures/bunker_sd/wirefence01
{
	cull none
	nomipmaps
	nopicmip
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	implicitMask -
}

textures/bunker_sd/concrete_c07bcmp_sand
{
    qer_editorimage textures/bunker_sd/concrete_c07bcmp_sand
	diffusemap textures/bunker_sd/concrete_c07bcmp_sand
	bumpmap textures/bunker_sd/concrete_c07bcmp_sand_n
	specularmap textures/bunker_sd/concrete_c07bcmp_sand_s
	implicitmap -
}

textures/bunker_sd/int_wall01
{
    qer_editorimage textures/bunker_sd/int_wall01
	diffusemap textures/bunker_sd/int_wall01
	bumpmap textures/bunker_sd/int_wall01_n
	specularmap textures/bunker_sd/int_wall01_s
	implicitmap -
}

textures/bunker_sd/int_wall01_rusty
{
    qer_editorimage textures/bunker_sd/int_wall01_rusty
	diffusemap textures/bunker_sd/int_wall01_rusty
	bumpmap textures/bunker_sd/int_wall01_rusty_n
	specularmap textures/bunker_sd/int_wall01_rusty_s
	implicitmap -
}

textures/bunker_sd/int_wall01_white
{
    qer_editorimage textures/bunker_sd/int_wall01_white
	diffusemap textures/bunker_sd/int_wall01_white
	bumpmap textures/bunker_sd/int_wall01_white_n
	specularmap textures/bunker_sd/int_wall01_white_s
	implicitmap -
}

textures/bunker_sd/int_wall07
{
    qer_editorimage textures/bunker_sd/int_wall07
	diffusemap textures/bunker_sd/int_wall07
	bumpmap textures/bunker_sd/int_wall07_n
	specularmap textures/bunker_sd/int_wall07_s
	implicitmap -
}

