// egypt_rock_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003 edited 28.02.2017 by thunder
// 7 total shaders

textures/egypt_rock_sd/layered_rock_01
{
    qer_Editorimage textures/egypt_rock_sd/layered_rock_01
	diffusemap textures/egypt_rock_sd/layered_rock_01
	bumpmap textures/egypt_rock_sd/layered_rock_01_n
	specularmap textures/egypt_rock_sd/layered_rock_01_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_rock_sd/layered_rock_01_btrim_01
{
    qer_editorimage textures/egypt_rock_sd/layered_rock_01_btrim_01
	diffusemap textures/egypt_rock_sd/layered_rock_01_btrim_01
	bumpmap textures/egypt_rock_sd/layered_rock_01_btrim_01_n
	specularmap textures/egypt_rock_sd/layered_rock_01_btrim_01_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_rock_sd/layered_rock_01_btrim_01_nero
{
	qer_editorimage textures/egypt_rock_sd/layered_rock_01_btrim_01
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_rock_sd/layered_rock_01_btrim_01
}

textures/egypt_rock_sd/layered_rock_01_nero
{
	qer_editorimage textures/egypt_rock_sd/layered_rock_01
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_rock_sd/layered_rock_01
}

textures/egypt_rock_sd/layered_rock_01_ttrim_01
{
    qer_editorimage textures/egypt_rock_sd/layered_rock_01_ttrim_01
	diffusemap textures/egypt_rock_sd/layered_rock_01_ttrim_01
	bumpmap textures/egypt_rock_sd/layered_rock_01_ttrim_01_n
	specularmap textures/egypt_rock_sd/layered_rock_01_ttrim_01_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_rock_sd/layered_rock_01_ttrim_01_nero
{
	qer_editorimage textures/egypt_rock_sd/layered_rock_01_ttrim_01
	diffusemap textures/egypt_rock_sd/layered_rock_01_ttrim_01
	bumpmap textures/egypt_rock_sd/layered_rock_01_ttrim_01_n
	specularmap textures/egypt_rock_sd/layered_rock_01_ttrim_01_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_rock_sd/layered_rock_01_ttrim_01
}

textures/egypt_rock_sd/sandstone_01
{
    qer_editorimage textures/egypt_rock_sd/sandstone_01
	diffusemap textures/egypt_rock_sd/sandstone_01
	bumpmap textures/egypt_rock_sd/sandstone_01_n
	specularmap textures/egypt_rock_sd/sandstone_01_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}
