// egypt_walls_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 21 total shaders

textures/egypt_walls_sd/stucco01_decor01_phong
{
    qer_editorimage textures/egypt_walls_sd/stucco01_decor01
	diffusemap textures/egypt_walls_sd/stucco01_decor01
	bumpmap textures/egypt_walls_sd/stucco01_decor01_n
	specularmap textures/egypt_walls_sd/stucco01_decor01_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_walls_sd/stucco01_decor01
}

textures/egypt_walls_sd/stucco01_phong
{
    qer_editorimage textures/egypt_walls_sd/stucco01
	diffusemap textures/egypt_walls_sd/stucco01
	bumpmap textures/egypt_walls_sd/stucco01_n
	specularmap textures/egypt_walls_sd/stucco01_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_walls_sd/stucco01
}

textures/egypt_walls_sd/stucco02
{
	qer_editorimage textures/egypt_walls_sd/stucco02
	diffusemap textures/egypt_walls_sd/stucco02
	bumpmap textures/egypt_walls_sd/stucco02_n
	specularmap textures/egypt_walls_sd/stucco02_s
	q3map_nonplanar
	q3map_shadeangle 60
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/egypt_walls_sd/stucco02
		blendFunc filter
	}
}

textures/egypt_walls_sd/stucco02_04blend
{
    qer_editorimage textures/egypt_walls_sd/stucco02_04blend
	diffusemap textures/egypt_walls_sd/stucco02_04blend
	bumpmap textures/egypt_walls_sd/stucco02_04blend_n
	specularmap textures/egypt_walls_sd/stucco02_04blend_s
	q3map_nonplanar
	q3map_shadeangle 30
	implicitMap -
}

textures/egypt_walls_sd/stucco03
{
    qer_editorimage textures/egypt_walls_sd/stucco03
	diffusemap textures/egypt_walls_sd/stucco03
	bumpmap textures/egypt_walls_sd/stucco03_n
	specularmap textures/egypt_walls_sd/stucco03_s
	q3map_nonplanar
	q3map_shadeangle 60
	implicitMap -
}

textures/egypt_walls_sd/stucco04
{
    qer_editorimage textures/egypt_walls_sd/stucco04
	diffusemap textures/egypt_walls_sd/stucco04
	bumpmap textures/egypt_walls_sd/stucco04_n
	specularmap textures/egypt_walls_sd/stucco04_s
	q3map_nonplanar
	q3map_shadeangle 60
	implicitMap -
}

textures/egypt_walls_sd/stucco07a
{
    qer_editormap textures/egypt_walls_sd/stucco07a
	diffusemap textures/egypt_walls_sd/stucco07a
	bumpmap textures/egypt_walls_sd/stucco07a_n
	specularmap textures/egypt_walls_sd/stucco07a_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco07a_nonsolid
{
    qer_editormap textures/egypt_walls_sd/stucco07a
	diffusemap textures/egypt_walls_sd/stucco07a
	bumpmap textures/egypt_walls_sd/stucco07a_n
	specularmap textures/egypt_walls_sd/stucco07a_s
	surfaceparm nonsolid
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_walls_sd/stucco07a
}

textures/egypt_walls_sd/stucco07b
{
    qer_editorimage textures/egypt_walls_sd/stucco07b
	diffusemap textures/egypt_walls_sd/stucco07b
	bumpmap textures/egypt_walls_sd/stucco07b_n
	specularmap textures/egypt_walls_sd/stucco07b_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco07c
{
    qer_editorimage textures/egypt_walls_sd/stucco07c
	diffusemap textures/egypt_walls_sd/stucco07c
	bumpmap textures/egypt_walls_sd/stucco07c_n
	specularmap textures/egypt_walls_sd/stucco07c_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco07d
{
    qer_editorimage textures/egypt_walls_sd/stucco07d
	diffusemap textures/egypt_walls_sd/stucco07d
	bumpmap textures/egypt_walls_sd/stucco07d_n
	specularmap textures/egypt_walls_sd/stucco07d_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08a
{
    qer_editorimage textures/egypt_walls_sd/stucco08a
	diffusemap textures/egypt_walls_sd/stucco08a
	bumpmap textures/egypt_walls_sd/stucco08a_n
	specularmap textures/egypt_walls_sd/stucco08a_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08b
{
    qer_editorimage textures/egypt_walls_sd/stucco08b
	diffusemap textures/egypt_walls_sd/stucco08b
	bumpmap textures/egypt_walls_sd/stucco08b_n
	specularmap textures/egypt_walls_sd/stucco08b_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08c
{
    qer_editorimage textures/egypt_walls_sd/stucco08c
	diffusemap textures/egypt_walls_sd/stucco08c
	bumpmap textures/egypt_walls_sd/stucco08c_n
	specularmap textures/egypt_walls_sd/stucco08c_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08d
{
    qer_editorimage textures/egypt_walls_sd/stucco08d
	diffusemap textures/egypt_walls_sd/stucco08d
	bumpmap textures/egypt_walls_sd/stucco08d_n
	specularmap textures/egypt_walls_sd/stucco08d_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08e
{
    qer_editorimage textures/egypt_walls_sd/stucco08e
	diffusemap textures/egypt_walls_sd/stucco08e
	bumpmap textures/egypt_walls_sd/stucco08e_n
	specularmap textures/egypt_walls_sd/stucco08e_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09a
{
    qer_editorimage textures/egypt_walls_sd/stucco09a
	diffusemap textures/egypt_walls_sd/stucco09a
	bumpmap textures/egypt_walls_sd/stucco09a_n
	specularmap textures/egypt_walls_sd/stucco09a_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09b
{
    qer_editorimage textures/egypt_walls_sd/stucco09b
	diffusemap textures/egypt_walls_sd/stucco09b
	bumpmap textures/egypt_walls_sd/stucco09b_n
	specularmap textures/egypt_walls_sd/stucco09b_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09c
{
    qer_editorimage textures/egypt_walls_sd/stucco09c
	diffusemap textures/egypt_walls_sd/stucco09c
	bumpmap textures/egypt_walls_sd/stucco09c_n
	specularmap textures/egypt_walls_sd/stucco09c_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09d
{
    qer_editorimage textures/egypt_walls_sd/stucco09d
	diffusemap textures/egypt_walls_sd/stucco09d
	bumpmap textures/egypt_walls_sd/stucco09d_n
	specularmap textures/egypt_walls_sd/stucco09d_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09e
{
    qer_editorimage textures/egypt_walls_sd/stucco09e
	diffusemap textures/egypt_walls_sd/stucco09e
	bumpmap textures/egypt_walls_sd/stucco09e_n
	specularmap textures/egypt_walls_sd/stucco09e_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09f
{
    qer_editorimage textures/egypt_walls_sd/stucco09f
	diffusemap textures/egypt_walls_sd/stucco09f
	bumpmap textures/egypt_walls_sd/stucco09f_n
	specularmap textures/egypt_walls_sd/stucco09f_s
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/wood_c05
{
    qer_editorimage textures/egypt_walls_sd/wood_c05
	diffusemap textures/egypt_walls_sd/wood_c05
	specularmap textures/egypt_walls_sd/wood_c05_s
	bumpmap textures/egypt_walls_sd/wood_c05_n
	surfaceparm woodsteps
	implicitMap -
}

textures/egypt_walls_sd/wood_c06
{
    qer_editorimage textures/egypt_walls_sd/wood_c06
	diffusemap textures/egypt_walls_sd/wood_c06
	bumpmap textures/egypt_walls_sd/wood_c06_n
	specularmap textures/egypt_walls_sd/wood_c06_s
	surfaceparm woodsteps
	implicitMap -
}

textures/egypt_walls_sd/wood_test
{
    qer_editorimage textures/egypt_walls_sd/wood_test
	diffusemap textures/egypt_walls_sd/wood_test
	bumpmap textures/egypt_walls_sd/wood_test_n
	specularmap textures/egypt_walls_sd/wood_test_s
	surfaceparm woodsteps
	implicitMap -
}
