// egypt_wood_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 2 total shaders

textures/egypt_wood_sd/wood1a
{
    qer_editorimage textures/egypt_wood_sd/wood1a
	diffusemap textures/egypt_wood_sd/wood1a
	bumpmap textures/egypt_wood_sd/wood1a_n
	specularmap textures/egypt_wood_sd/wood1a_s
	surfaceparm woodsteps
	implicitMap -
}

textures/egypt_wood_sd/wood1b
{
    qer_editorimage textures/egypt_wood_sd/wood1b
	diffusemap textures/egypt_wood_sd/wood1b
	bumpmap textures/egypt_wood_sd/wood1b_n
	specularmap textures/egypt_wood_sd/wood1b_s
	surfaceparm woodsteps
	implicitMap -
}
