// props.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
//
// edited by ThomasC on 18-03-2003
//
// 57 total shaders

textures/props/barrel_m01
{
    qer_editorimage textures/props/barrel_m01
	diffusemap textures/props/barrel_m01
	bumpmap textures/props/barrel_m01_n
	specularmap textures/props/barrel_m01_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/barrel_m02
{
    qer_editorimage textures/props/barrel_m02
	diffusemap textures/props/barrel_m02
	bumpmap textures/props/barrel_m02_n
	specularmap textures/props/barrel_m02_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/barrel_m02d
{
    qer_editorimage textures/props/barrel_m02d
	diffusemap textures/props/barrel_m02d
	bumpmap textures/props/barrel_m02d_n
	specularmap textures/props/barrel_m02d_s
	surfaceparm metalsteps
	implicitMap -
}
textures/props/base_lamp_1
{
	qer_editorimage textures/props/base_lamp
	diffusemap textures/props/base_lamp
	bumpmap textures/props/base_lamp_n
	specularmap textures/props/base_lamp_s
        surfaceparm nomarks
        surfaceparm pointlight
 	surfaceparm nolightmap

	implicitMap textures/props/base_lamp
}

textures/props/base_lamp_1_oasis
{
	qer_editorimage textures/props/base_lamp
	diffusemap textures/props/base_lamp
	bumpmap textures/props/base_lamp_n
	specularmap textures/props/base_lamp_s
        surfaceparm nomarks
        surfaceparm pointlight
 	surfaceparm nolightmap
	surfaceparm trans

	{
		map textures/props/base_lamp
		rgbGen identity
	}
}

textures/props/board_cl01
{
    qer_editorimage textures/props/board_cl01
	diffusemap textures/props/board_cl01
	bumpmap textures/props/board_cl01_n
	specularmap textures/props/board_cl01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/board_cl01m
{
    qer_editorimage textures/props/board_cl01m
	diffusemap textures/props/board_cl01m
	bumpmap textures/props/board_cl01m_n
	specularmap textures/props/board_cl01m_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/board_c01
{
    qer_editorimage textures/props/board_c01
	diffusemap textures/props/board_c01
	bumpmap textures/props/board_c01_n
	specularmap textures/props/board_c01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/board_c03
{
    qer_editorimage textures/props/board_c03
	diffusemap textures/props/board_c03
	bumpmap textures/props/board_c03_n
	specularmap textures/props/board_c03_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/board_m01
{
    qer_editorimage textures/props/board_m01
	diffusemap textures/props/board_m01
	bumpmap textures/props/board_m01_n
	specularmap textures/props/board_m01_s
	surfaceparm woodsteps
	implicitMap -
}
//extra shader
textures/props/board_cl02m
{
    qer_editorimage textures/props/board_cl02m
	diffusemap textures/props/board_cl02m
	bumpmap textures/props/board_cl02m_n
	specularmap textures/props/board_cl02m_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_c01
{
    qer_editorimage textures/props/box_c01
	diffusemap textures/props/box_c01
	bumpmap textures/props/box_c01_n
	specularmap textures/props/box_c01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_c02
{
     qer_editorimage textures/props/box_c02
	diffusemap textures/props/box_c02
	bumpmap textures/props/box_c02_n
	specularmap textures/props/box_c02_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_c03
{
     qer_editorimage textures/props/box_c03
	diffusemap textures/props/box_c03
	bumpmap textures/props/box_c03_n
	specularmap textures/props/box_c03_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_m01
{
    qer_editorimage textures/props/box_m01
	diffusemap textures/props/box_m01
	bumpmap textures/props/box_m01_n
	specularmap textures/props/box_m01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_m02
{
    qer_editorimage textures/props/box_m02
	diffusemap textures/props/box_m02
	bumpmap textures/props/box_m02_n
	specularmap textures/props/box_m02_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_m03
{
    qer_editorimage textures/props/box_m03
	diffusemap textures/props/box_m03
	bumpmap textures/props/box_m03_n
	specularmap textures/props/box_m03_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_m04
{
    qer_editorimage textures/props/box_m04
    diffusemap textures/props/box_m04
    bumpmap textures/props/box_m04_n
    specularmap textures/props/box_m04_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_m04a
{
    qer_editorimage textures/props/box_m04a
	diffusemap textures/props/box_m04a
	bumpmap textures/props/box_m04a_n
	specularmap textures/props/box_m04a_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_m04a_sd
{
    qer_editorimage textures/props/box_m04a_sd
	diffusemap textures/props/box_m04a_sd
	bumpmap textures/props/box_m04a_sd_n
	specularmap textures/props/box_m04a_sd_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_m05
{
    qer_editorimage textures/props/box_m05
	diffusemap textures/props/box_m05
	bumpmap textures/props/box_m05_n
	specularmap textures/props/box_m05_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_m05a
{
    qer_editorimage textures/props/box_m05a
	diffusemap textures/props/box_m05a
	bumpmap textures/props/box_m05a_n
	specularmap textures/props/box_m05a_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_t_m01
{
    qer_editorimage textures/props/box_t_m01
	diffusemap textures/props/box_t_m01
	bumpmap textures/props/box_t_m01_n
	specularmap textures/props/box_t_m01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_t_m01a
{
    qer_editorimage textures/props/box_t_m01a
	diffusemap textures/props/box_t_m01a
	bumpmap textures/props/box_t_m01a_n
	specularmap textures/props/box_t_m01a_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_t_m02
{
    qer_editorimage textures/props/box_t_m02
	diffusemap textures/props/box_t_m02
	bumpmap textures/props/box_t_m02_n
	specularmap textures/props/box_t_m02_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_t_m04
{
    qer_editorimage textures/props/box_t_m04
	diffusemap textures/props/box_t_m04
	bumpmap textures/props/box_t_m04_n
	specularmap textures/props/box_t_m04_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_t_m04a
{
    qer_editorimage textures/props/box_t_m04a
	diffusemap textures/props/box_t_m04a
	bumpmap textures/props/box_t_m04a_n
	specularmap textures/props/box_t_m04a_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/box_t_m04b
{
    qer_editorimage textures/props/box_t_m04b
	diffusemap textures/props/box_t_m04b
	bumpmap textures/props/box_t_m04b_n
	specularmap textures/props/box_t_m04b_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/cable_m01
{
    qer_editorimage textures/props/cable_m01
	diffusemap textures/props/cable_m01
	bumpmap textures/props/cable_m01_n
	specularmap textures/props/cable_m01_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/flag_l_m01
{
	cull twosided
	deformVertexes wave 10 sin 0 2 0 .2
	surfaceparm alphashadow
	surfaceparm pointlight
	surfaceparm trans
	implicitBlend -
}

textures/props/flag_l_m01_tad
{
	cull twosided
	surfaceparm alphashadow
	surfaceparm pointlight
	surfaceparm trans
	implicitBlend -
}

textures/props/flag_l_m01nomove
{
	qer_editorimage textures/props/flag_l_m01
	cull twosided
	surfaceparm alphashadow
	surfaceparm pointlight
	surfaceparm trans
	implicitBlend textures/props/flag_l_m01
}

textures/props/flags_m1
{
	cull twosided
	deformVertexes wave 10 sin 0 2 0 .2
	surfaceparm alphashadow
	surfaceparm pointlight
	surfaceparm trans
	implicitBlend -
}

textures/props/flags_m1_fac
{
	qer_trans 0.90
	cull twosided
	deformVertexes wave 10 sin 0 2 0 .2
	surfaceparm alphashadow
	surfaceparm pointlight
	surfaceparm trans
	implicitBlend -
}

textures/props/flags_m1_snow
{
	cull twosided
	deformVertexes wave 10 sin 0 2 0 .2
	surfaceparm alphashadow
	surfaceparm trans
	implicitMask -
}

textures/props/freeze_glass
{
	deformVertexes wave 64 sin .25 .25 0 .5
	surfaceparm trans
	{
		map textures/props/freeze_cloud
		blendFunc GL_dst_color GL_one
		tcmod scale -2 -2
		tcmod scroll .0 -0.20
	}
	{
		map textures/props/freeze_glass
		blendFunc GL_dst_color GL_one
		tcmod scale 1 1
		tcmod scroll .05 .025
	}
	{
		map $lightmap
		blendFunc GL_dst_color GL_zero
		rgbgen identity
	}
}

textures/props/fwindow1
{
	surfaceparm trans
	{
		map textures/props/fwindow1
		blendFunc GL_ONE GL_SRC_ALPHA
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ONE_MINUS_DST_ALPHA
		rgbGen identity
	}
}

textures/props/fwindow1_1
{
	qer_editorimage textures/props/fwindow1
        surfaceparm nomarks
        surfaceparm pointlight
 	surfaceparm nolightmap
	surfaceparm trans
	{
		map textures/props/fwindow1
		blendFunc GL_ONE GL_ONE
		rgbGen lightingdiffuse
	}
}

textures/props/fwindow1_1_oasis
{
	qer_editorimage textures/props/fwindow1
        surfaceparm nomarks
        surfaceparm pointlight
 	surfaceparm nolightmap
	surfaceparm trans
	{
		map textures/props/fwindow1
		blendFunc GL_ONE GL_ONE
		rgbGen lightingdiffuse
	}
}

textures/props/hay
{
    qer_editorimage textures/props/hay
	diffusemap textures/props/hay
	bumpmap textures/props/hay_n
	specularmap textures/props/hay_s
	surfaceparm grasssteps
	implicitMap -
}

textures/props/hayd
{
    qer_editorimage textures/props/hayd
	diffusemap textures/props/hayd
	bumpmap textures/props/hayd_n
	specularmap textures/props/hayd_s
	surfaceparm grasssteps
	implicitMap -
}

textures/props/lockers_c01
{
    qer_editorimage textures/props/lockers_c01
	diffusemap textures/props/lockers_c01
	bumpmap textures/props/lockers_c01_n
	specularmap textures/props/lockers_c01_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/lockers_c02
{
    qer_editorimage textures/props/lockers_c02
	diffusemap textures/props/lockers_c02
	bumpmap textures/props/lockers_c02_n
	specularmap textures/props/lockers_c02_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/panel_d03
{
    qer_editorimage textures/props/panel_d03
	diffusemap textures/props/panel_d03
	bumpmap textures/props/panel_d03_n
	specularmap textures/props/panel_d03_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/panel_d04
{
    qer_editorimage textures/props/panel_d04
	diffusemap textures/props/panel_d04
	bumpmap textures/props/panel_d04_n
	specularmap textures/props/panel_d04_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/panel_tram2
{
    qer_editorimage textures/props/panel_tram2
	diffusemap textures/props/panel_tram2
	bumpmap textures/props/panel_tram2_n
	specularmap textures/props/panel_tram2_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/panel_tram3
{
    qer_editorimage textures/props/panel_tram3
	diffusemap textures/props/panel_tram3
	bumpmap textures/props/panel_tram3_n
	specularmap textures/props/panel_tram3_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/panelside_d01
{
    qer_editorimage textures/props/panelside_d01
	diffusemap textures/props/panelside_d01
	bumpmap textures/props/panelside_d01_n
	specularmap textures/props/panelside_d01_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/rail_side_wils
{
    qer_editorimage textures/props/rail_side_wils
	diffusemap textures/props/rail_side_wils
	bumpmap textures/props/rail_side_wils_n
	specularmap textures/props/rail_side_wils_s
	surfaceparm metalsteps
	implicitMap -
}


textures/props/rail_top_wils
{
    qer_editorimage textures/props/rail_top_wils
	diffusemap textures/props/rail_top_wils
	bumpmap textures/props/rail_top_wils_n
	specularmap textures/props/rail_top_wils_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/refer_light
{
	qer_editorimage textures/props/refer
	q3map_lightimage textures/lights/lgreen
	q3map_surfacelight 150
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/props/refer
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/props/refer
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

//new ones
textures/props/rope_m01
{
    qer_editorimage textures/props/rope_m01
	diffusemap textures/props/rope_m01
	bumpmap textures/props/rope_m01_n
	specularmap textures/props/rope_m01_s
	surfaceparm woodsteps
	implicitmap -
}

textures/props/sawblade
{
    qer_editorimage textures/props/sawblade
	diffusemap textures/props/sawblade
	bumpmap textures/props/sawblade_n
	specularmap textures/props/sawblade_s
	surfaceparm metalsteps
	implicitMap -
}
// end new ones

textures/props/sho_box_c01
{
    qer_editorimage textures/props/sho_box_c01
	diffusemap textures/props/sho_box_c01
	bumpmap textures/props/sho_box_c01_n
	specularmap textures/props/sho_box_c01_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/sho_box_c02
{
    qer_editorimage textures/props/sho_box_c02
	diffusemap textures/props/sho_box_c02
	bumpmap textures/props/sho_box_c02_n
	specularmap textures/props/sho_box_c02_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/sho_box_c03
{
    qer_editorimage textures/props/sho_box_c03
	diffusemap textures/props/sho_box_c03
	bumpmap textures/props/sho_box_c03_n
	specularmap textures/props/sho_box_c03_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/sign_c01
{
    qer_editorimage textures/props/sign_c01
	diffusemap textures/props/sign_c01
	bumpmap textures/props/sign_c01_n
	specularmap textures/props/sign_c01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/sign_c05
{
    qer_editorimage textures/props/sign_c05
	diffusemap textures/props/sign_c05
	bumpmap textures/props/sign_c05_n
	specularmap textures/props/sign_c05_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/sign_c06
{
    qer_editorimage textures/props/sign_c06
	diffusemap textures/props/sign_c06
	bumpmap textures/props/sign_c06_n
	specularmap textures/props/sign_c06_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/sign_c26
{
    qer_editorimage textures/props/sign_c26
	diffusemap textures/props/sign_c26
	bumpmap textures/props/sign_c26_n
	specularmap textures/props/sign_c26_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/sign_c27
{
    qer_editorimage textures/props/sign_c27
	diffusemap textures/props/sign_c27
	bumpmap textures/props/sign_c27_n
	specularmap textures/props/sign_c27_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/sub1
{
    qer_editorimage textures/props/sub1
	diffusemap textures/props/sub1
	bumpmap textures/props/sub1_n
	specularmap textures/props/sub1_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/table
{
    qer_editorimage textures/props/table
	diffusemap textures/props/table
	bumpmap textures/props/table_n
	specularmap textures/props/table_s
	surfaceparm metalsteps
	surfaceparm pointlight
	{
		map models/mapobjects/deadosa/elec1
		rgbGen identity
		tcMod scale 2 2
		tcMod scroll 2 2
	}
	{
		map textures/props/table
		blendfunc blend
		rgbGen vertex
	}
}

textures/props/torch_ember
{
	qer_editorimage textures/props/torch_ember
	surfaceparm pointlight
	surfaceparm woodsteps
	{
		map textures/props/ember1a
		rgbGen wave sin 1 0.5 0 0.5
		tcmod rotate 3
	}
	{
		map textures/props/torch_ember
		blendfunc blend
		rgbGen vertex
	}
}

textures/props/train_m01
{
    qer_editorimage textures/props/train_m01
	diffusemap textures/props/train_m01
	bumpmap textures/props/train_m01_n
	specularmap textures/props/train_m01_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/train_m02
{
    qer_editorimage textures/props/train_m02
	diffusemap textures/props/train_m02
	bumpmap textures/props/train_m02_n
	specularmap textures/props/train_m02_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/train_m03
{
    qer_editorimage textures/props/train_m03
	diffusemap textures/props/train_m03
	bumpmap textures/props/train_m03_n
	specularmap textures/props/train_m03_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/train_m04
{
    qer_editorimage textures/props/train_m04
	diffusemap textures/props/train_m04
	bumpmap textures/props/train_m04_n
	specularmap textures/props/train_m04_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/train_m05
{
    qer_editorimage textures/props/train_m05
	diffusemap textures/props/train_m05
	bumpmap textures/props/train_m05_n
	specularmap textures/props/train_m05_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/train_m06
{
    qer_editorimage textures/props/train_m06
	diffusemap textures/props/train_m06
	bumpmap textures/props/train_m06_n
	specularmap textures/props/train_m06_s
	surfaceparm metalsteps
	implicitMap -
}

textures/props/wine_c01
{
    qer_editorimage textures/props/wine_c01
	diffusemap textures/props/wine_c01
	bumpmap textures/props/wine_c01_n
	specularmap textures/props/wine_c01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/props/wine_c02
{
    qer_editorimage textures/props/wine_c02
	diffusemap textures/props/wine_c02
	bumpmap textures/props/wine_c02_n
	specularmap textures/props/wine_c02_s
    surfaceparm woodsteps
	implicitMap -
}

textures/props/file_cab_m01
{
    qer_editorimage textures/props/file_cab_m01
	diffusemap textures/props/file_cab_m01
	bumpmap textures/props/file_cab_m01_n
	specularmap textures/props/file_cab_m01_s
	surfaceparm metalsteps
	implicitMap -
}
