// railgun_props.shader
// generated by ThomasC
// 1 total shader

textures/railgun_props/tug_side
{
    qer_editormap textures/railgun_props/tug_side
	diffusemap textures/railgun_props/tug_side
	bumpmap textures/railgun_props/tug_side_n
	specularmap textures/railgun_props/tug_side_s
	surfaceparm metalsteps
	implicitMap -
}