// town_window.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// updated for etl 2017 thunder
// 1 total shaders

textures/town_window/shudder_c04
{
    qer_editorimage textures/town_window/shudder_c04
	diffusemap textures/town_window/shudder_c04
	specularmap textures/town_window/shudder_c04_s
	bumpmap textures/town_window/shudder_c04_n
	surfaceparm woodsteps
	implicitMap -
}
