// alpha.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 32 total shaders
//
// 20/03/03 Added surfaceparm nomarks to all alpha textures
// 22/02/17 Added stages diffuse,normal and spec...and qer_editorimage Thunder

textures/alpha/barb_wire
{
    qer_editorimage textures/alpha/barb_wire
    diffuseMap textures/alpha/barb_wire
	bumpMap textures/alpha/barb_wire_n
	specularMap textures/alpha/barb_wire_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/barb_wire_clip
{
	qer_editorimage textures/alpha/barb_wire
	diffuseMap textures/alpha/barb_wire
	bumpMap textures/alpha/barb_wire_n
	specularMap textures/alpha/barb_wire_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm pointlight
	surfaceparm trans
	implicitMask textures/alpha/barb_wire.tga
}

textures/alpha/bars_m01
{
    qer_editorimage textures/alpha/bars_m01
	diffuseMap textures/alpha/bars_m01
	bumpMap textures/alpha/bars_m01_n
	specularMap textures/alpha/bars_m01_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/bel_orn_m01
{
    qer_editorimage textures/alpha/bel_orn_m01
	diffuseMap textures/alpha/bel_orn_m01
	bumpMap textures/alpha/bel_orn_m01_n
	specularMap textures/alpha/bel_orn_m01_s
	surfaceparm nomarks
	surfaceparm pointlight
	surfaceparm trans
	nopicmip
	implicitBlend -
}

textures/alpha/chateau_c06a
{
    qer_editorimage textures/alpha/chateau_c06a
	diffuseMap textures/alpha/chateau_c06a
	bumpMap textures/alpha/chateau_c06a_n
	specularMap textures/alpha/chateau_c06a_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

// This is more or less similiar to clipmissile
// The other five faces of the brush should be clipmissle

textures/alpha/chateau_c06a_clipmissle
{
	qer_trans 0.85
	qer_editorimage textures/alpha/chateau_c06a
	diffuseMap textures/alpha/chateau_c06a
	bumpMap textures/alpha/chateau_c06a_n
	specularMap textures/alpha/chateau_c06a_s
	cull disable
	nomipmaps
	nopicmip

	surfaceparm clipmissile
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm playerclip
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans

	implicitMask textures/alpha/chateau_c06a.tga
}

textures/alpha/chateau_c07
{
    qer_editorimage textures/alpha/chateau_c07
	diffuseMap textures/alpha/chateau_c07
	bumpMap textures/alpha/chateau_c07_n
	specularMap textures/alpha/chateau_c07_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

// This is more or less similiar to clipmissile
// The other five faces of the brush should be clipmissle

textures/alpha/chateau_c07_clipmissle
{
	qer_trans 0.85
	qer_editorimage textures/alpha/chateau_c07
	diffuseMap textures/alpha/chateau_c07
	bumpMap textures/alpha/chateau_c07_n
	specularMap textures/alpha/chateau_c07_s
	cull disable
	nomipmaps
	nopicmip

	surfaceparm clipmissile
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm playerclip
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans

	implicitMask textures/alpha/chateau_c07.tga
}

textures/alpha/chateau_c08
{
    qer_editorimage textures/alpha/chateau_c08
	diffuseMap textures/alpha/chateau_c08
	bumpMap textures/alpha/chateau_c08
	specularMap textures/alpha/chateau_c08_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitBlend -
}

textures/alpha/chateau_c08_wils
{
	qer_editorimage textures/alpha/chateau_c08
	diffuseMap textures/alpha/chateau_c08
	bumpMap textures/alpha/chateau_c08
	specularMap textures/alpha/chateau_c08_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask textures/alpha/chateau_c08.tga
}

textures/alpha/chateau_c09
{
    qer_editorimage textures/alpha/chateau_c09
	diffuseMap textures/alpha/chateau_c09
	bumpMap textures/alpha/chateau_c09_n
	specularMap textures/alpha/chateau_c09_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/chateau_c11
{
    qer_editorimage textures/alpha/chateau_c11
	diffuseMap textures/alpha/chateau_c11
	bumpMap textures/alpha/chateau_c11_n
	specularMap textures/alpha/chateau_c11_S
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	{
		map textures/alpha/chateau_c11
		alphaFunc GE128
		rgbGen vertex
	}
}

// This is more or less similiar to clipmissile
// The other five faces of the brush should be clipmissle
textures/alpha/chateau_c11_clipmissle
{
	qer_trans 0.85
	qer_editorimage textures/alpha/chateau_c11
	diffuseMap textures/alpha/chateau_c11
	bumpMap textures/alpha/chateau_c11_n
	specularMap textures/alpha/chateau_c11_s
	cull disable
	nomipmaps
	nopicmip

	surfaceparm clipmissile
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm playerclip
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans

	implicitMask textures/alpha/chateau_c11
}

textures/alpha/chateau_c14
{
    qer_editorimage textures/alpha/chateau_c14
	diffuseMap textures/alpha/chateau_c14
	bumpMap textures/alpha/chateau_c14_n
	specularMap textures/alpha/chateau_c14_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/cweb_m01a
{
    qer_editorimage textures/alpha/cweb_m01a
	diffuseMap textures/alpha/cweb_m01a
	bumpMap textures/alpha/cweb_m01a_n
	specularMap textures/alpha/cweb_m01a_s
	qer_trans 0.8
	cull disable
	deformVertexes wave 10 sin 0 2 0 0.2
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm nonsolid
	surfaceparm pointlight
	surfaceparm trans
	implicitBlend -
}

textures/alpha/fence_c05
{
    qer_editorimage textures/alpha/fence_c05
	diffuseMap textures/alpha/fence_c05
	bumpMap textures/alpha/fence_c05_n
	specularMap textures/alpha/fence_c05_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/fence_c10
{
    qer_editorimage textures/alpha/fence_c10
	diffuseMap textures/alpha/fence_c10
	bumpMap textures/alpha/fence_c10_n
	specularMap textures/alpha/fence_c10_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/fence_c11
{
    qer_editorimage textures/alpha/fence_c11
	diffuseMap textures/alpha/fence_c11
	bumpmap textures/alpha/fence_c11_n
	specularMap textures/alpha/fence_c11_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/fence_c14
{
    qer_editorimage textures/alpha/fence_c14
	diffuseMap textures/alpha/fence_c14
	bumpMap textures/alpha/fence_c14_n
	specularMap textures/alpha/fence_c14_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

// This is more or less similiar to clipmissile
// The other five faces of the brush should be clipmissle
textures/alpha/fence_c14_clipmissle
{
	qer_trans 0.85
	qer_editorimage textures/alpha/fence_c14
	diffuseMap textures/alpha/fence_c14
	bumpMap textures/alpha/fence_c14_n
	specularMap textures/alpha/fence_c14_s
	cull disable
	nomipmaps
	nopicmip

	surfaceparm clipmissile
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm playerclip
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans

	implicitMask textures/alpha/fence_c14
}

textures/alpha/fence_m01
{
    qer_editorimage textures/alpha/fence_m01
	diffuseMap textures/alpha/fence_m01
	bumpMap textures/alpha/fence_m01_n
	specularMap textures/alpha/fence_m01_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/fence_m01b
{
    qer_editorimage textures/alpha/fence_m01b
	diffuseMap textures/alpha/fence_m01b
	bumpMap textures/alpha/fence_m01b_n
	specularMap textures/alpha/fence_m01b_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/fence_m02
{
    qer_editorimage textures/alpha/fence_m02
	diffuseMap textures/alpha/fence_m02
	bumpMap textures/alpha/fence_m02_n
	specularMap textures/alpha/fence_m02_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/fence_m03
{
    qer_editorimage textures/alpha/fence_m03
	diffuseMap textures/alpha/fence_m03
	bumpMap textures/alpha/fence_m03_n
	specularMap textures/alpha/fence_m03_s
	qer_trans 0.5
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/fence_m04
{
    qer_editorimage textures/alpha/fence_m04
	diffuseMap textures/alpha/fence_m04
	bumpMap textures/alpha/fence_m04_n
	specularMap textures/alpha/fence_m04_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/fence_m06
{
    qer_editorimage textures/alpha/fence_m06
	diffuseMap textures/alpha/fence_m06
	bumpMap textures/alpha/fence_m06_n
	specularMap textures/alpha/fence_m06_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/fence_m06b
{
    qer_editorimage textures/alpha/fence_m06b
	diffuseMap textures/alpha/fence_m06b
	bumpMap textures/alpha/fence_m06b_n
	specularMap textures/alpha/fence_m06b_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/hay
{
	qer_editorimage textures/props/hay
	diffuseMap textures/props/hay
	bumpMap textures/props/hay_n
	specularMap textures/props/hay_s
	cull disable
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	nopicmip
	implicitMask textures/props/hay
}

textures/alpha/ladder
{
    qer_editorimage textures/alpha/ladder
	diffuseMap textures/alpha/ladder
	bumpMap textures/alpha/ladder_n
	specularMap textures/alpha/ladder_s
	cull disable
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	nopicmip
	implicitMask -
}

textures/alpha/mesh_c02
{
    qer_editorimage textures/alpha/mesh_c02
	diffuseMap textures/alpha/mesh_c02
	bumpMap textures/alpha/mesh_c02_n
	specularMap textures/alpha/mesh_c02_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

// This is more or less similiar to clipmissile
// The other five faces of the brush should be clipmissle
textures/alpha/mesh_c02_clipmissle
{
	qer_trans 0.85
	qer_editorimage textures/alpha/mesh_c02
	diffuseMap textures/alpha/mesh_c02
	bumpMap textures/alpha/mesh_c02_n
	specularMap textures/alpha/mesh_c02_s
	cull disable
	nomipmaps
	nopicmip

	surfaceparm clipmissile
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm playerclip
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans

	implicitMask textures/alpha/mesh_c02
}

textures/alpha/mesh_c03
{
    qer_editorimage textures/alpha/mesh_c03
	diffuseMap textures/alpha/mesh_c03
	bumpMap textures/alpha/mesh_c03_n
	specularMap textures/alpha/mesh_c03_s
	cull twosided
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm playerclip
	surfaceparm clipmissile
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/truss_m03
{
    qer_editorimage textures/alpha/truss_m03
	diffuseMap textures/alpha/truss_m03
	bumpMap textures/alpha/truss_m03_n
	specularMap textures/alpha/truss_m03_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/truss_m06
{
    qer_editorimage textures/alpha/truss_m06
	diffuseMap textures/alpha/truss_m06
	bumpMap textures/alpha/truss_m06_n
	specularMap textures/alpha/truss_m06_S
	cull disable
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	nopicmip
	implicitMask -
}

textures/alpha/truss_m06a
{
    qer_editorimage textures/alpha/truss_m06a
	diffuseMap textures/alpha/truss_m06a
	bumpMap textures/alpha/truss_m06a_n
	specularMap textures/alpha/truss_m06a_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/truss_m06r
{
    qer_editorimage textures/alpha/truss_m06r
	diffuseMap textures/alpha/truss_m06r
	bumpMap textures/alpha/truss_m06r_n
	specularMap textures/alpha/truss_m06r_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/alpha/truss_m07
{
    qer_editorimage textures/alpha/truss_m07
	diffuseMap textures/alpha/truss_m07
	bumpMap textures/alpha/truss_m07_n
	specularMap textures/alpha/truss_m07_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}
