// assault.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 14 total shaders

textures/assault/atool_m02
{
    qer_editorimage textures/assault/atool_m02
	diffuseMap textures/assault/atool_m02
	bumpMap textures/assault/atool_m02_n
	specularMap textures/assault/atool_m02_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/atruss_m06a
{
    qer_editorimage textures/assault/atruss_m06a
	diffuseMap textures/assault/atruss_m06a
	bumpMap textures/assault/atruss_m06a_n
	specularMap textures/assault/atruss_m06a_s
	cull disable
	nomipmaps
	nopicmip
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/assault/machine_cl01
{
    qer_editorimage textures/assault/machine_cl01
	diffuseMap textures/assault/machine_cl01
	bumpMap textures/assault/machine_cl01_n
	specularMap textures/assault/machine_cl01_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c01b
{
    qer_editorimage textures/assault/machine_c01b
	diffuseMap textures/assault/machine_c01b
	bumpMap textures/assault/machine_c01b_n
	specularMap textures/assault/machine_c01b_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c03a
{
    qer_editorimage textures/assault/machine_c03a
	diffuseMap textures/assault/machine_c03a
	bumpMap textures/assault/machine_c03a_n
	specularMap textures/assault/machine_c03a_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c03e
{
    qer_editorimage textures/assault/machine_c03e
	diffuseMap textures/assault/machine_c03e
	bumpMap textures/assault/machine_c03e_n
	specularMap textures/assault/machine_c03e_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c04b
{
    qer_editorimage textures/assault/machine_c04b
	diffuseMap textures/assault/machine_c04b
	bumpMap textures/assault/machine_c04b_n
	specularMap textures/assault/machine_c04b_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c05b
{
    qer_editorimage textures/assault/machine_c05b
	diffuseMap textures/assault/machine_c05b
	bumpMap textures/assault/machine_c05b_n
	specularMap textures/assault/machine_c05b_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c06b
{
    qer_editorimage textures/assault/machine_c06b
	diffuseMap textures/assault/machine_c06b
	bumpMap textures/assault/machine_c06b_n
	specularMap textures/assault/machine_c06b_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c07
{
    qer_editorimage textures/assault/machine_c07
	diffuseMap textures/assault/machine_c07
	bumpMap textures/assault/machine_c07_n
	specularMap textures/assault/machine_c07_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/metal_c06
{
    qer_editorimage textures/assault/metal_c06
	diffuseMap textures/assault/metal_c06
	bumpMap textures/assault/metal_c06_n
	specularMap textures/assault/metal_c06_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/metal_c07a
{
    qer_editorimage textures/assault/metal_c07a
	diffuseMap textures/assault/metal_c07a
	bumpMap textures/assault/metal_c07a_n
	specularMap textures/assault/metal_c07a_s
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/metal_c07ans
{
	qer_editorimage textures/assault/metal_c07a
	diffuseMap textures/assault/metal_c07ans
	bumpMap textures/assault/metal_c07ans_n
	specularMap textures/assault/metal_c07ans_s
	surfaceparm nonsolid
	surfaceparm trans
	implicitMap textures/assault/metal_c07a
}

textures/assault/trim_c01
{
    qer_editorimage textures/assault/trim_c01
	diffusemap textures/assault/trim_c01
	bumpMap textures/assault/trim_c01_n
	specularMap textures/assault/trim_c01_s
	surfaceparm metalsteps
	implicitMap -
}
