// castle_wood.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 6 total shaders

textures/castle_wood/cwood_c10
{
    qer_editorimage textures/castle_wood/cwood_c10
	diffusemap textures/castle_wood/cwood_c10
	bumpmap textures/castle_wood/cwood_c10_n
	specularmap textures/castle_wood/cwood_c10_s
	surfaceparm woodsteps
	implicitMap -
}

textures/castle_wood/cwood_c18
{
    qer_editorimage textures/castle_wood/cwood_c18
	diffusemap textures/castle_wood/cwood_c18
	bumpmap textures/castle_wood/cwood_c18_n
	specularmap textures/castle_wood/cwood_c18_s
	surfaceparm woodsteps
	implicitMap -
}

textures/castle_wood/cwood_mo2s1
{
    qer_editorimage textures/castle_wood/cwood_mo2s1
	diffusemap textures/castle_wood/cwood_mo2s1
	bumpmap textures/castle_wood/cwood_mo2s1_n
	specularmap textures/castle_wood/cwood_mo2s1_s
	surfaceparm woodsteps
	implicitMap -
}

textures/castle_wood/cwood_mo5c
{
    qer_editorimage textures/castle_wood/cwood_mo5c
	diffusemap textures/castle_wood/cwood_mo5c
	bumpmap textures/castle_wood/cwood_mo5c_n
	specularmap textures/castle_wood/cwood_mo5c_s
	surfaceparm woodsteps
	implicitMap -
}

textures/castle_wood/cwood_mo5cb
{
    qer_editorimage textures/castle_wood/cwood_mo5cb
	diffusemap textures/castle_wood/cwood_mo5cb
	bumpmap textures/castle_wood/cwood_mo5cb_n
	specularmap textures/castle_wood/cwood_mo5cb_s
	surfaceparm woodsteps
	implicitMap -
}

textures/castle_wood/cwood_mo6
{
    qer_editorimage textures/castle_wood/cwood_mo6
	diffusemap textures/castle_wood/cwood_mo6
	bumpmap textures/castle_wood/cwood_mo6_n
	specularmap textures/castle_wood/cwood_mo6_s
	surfaceparm woodsteps
	implicitMap -
}
