// chateau.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 36 total shaders

textures/chateau/desk_c03
{
    qer_editorimage textures/chateau/desk_c03
	diffusemap textures/chateau/desk_c03
	bumpmap textures/chateau/desk_c03_n
	specularmap textures/chateau/desk_c03_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/desk_c04
{
    qer_editorimage textures/chateau/desk_c04
	diffusemap textures/chateau/desk_c04
	bumpmap textures/chateau/desk_c04_n
	specularmap textures/chateau/desk_c04_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/door_c01
{
    qer_editorimage textures/chateau/door_c01
	diffusemap textures/chateau/door_c01
	bumpmap textures/chateau/door_c01_n
	specularmap textures/chateau/door_c01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/fireplace_01
{
    qer_editorimage textures/chateau/fireplace_01
	diffusemap textures/chateau/fireplace_01
	bumpmap textures/chateau/fireplace_01_n
	specularmap textures/chateau/fireplace_01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/floor_c04
{
    qer_editorimage textures/chateau/floor_c04
	diffusemap textures/chateau/floor_c04
	bumpmap textures/chateau/floor_c04_n
	specularmap textures/chateau/floor_c04_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/floor_c05
{
    qer_editorimage textures/chateau/floor_c05
	diffusemap textures/chateau/floor_c05
	bumpmap textures/chateau/floor_c05_n
	specularmap textures/chateau/floor_c05_S
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/floor_c06
{
    qer_editorimage textures/chateau/floor_c06
	diffusemap textures/chateau/floor_c06
	bumpmap textures/chateau/floor_c06_n
	specularmap textures/chateau/floor_c06_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/floor_c10
{
    qer_editorimage textures/chateau/floor_c10
	diffusemap textures/chateau/floor_c10
	bumpmap textures/chateau/floor_c10_n
	specularmap textures/chateau/floor_c10_s
	surfaceparm carpetsteps
	implicitMap -
}

textures/chateau/floor_c10a
{
    qer_editorimage textures/chateau/floor_c10a
	diffusemap textures/chateau/floor_c10a
	bumpmap textures/chateau/floor_c10a_n
	specularmap textures/chateau/floor_c10a_s
	surfaceparm carpetsteps
	implicitMap -
}

textures/chateau/pillar_temp_rf
{
    qer_editorimage textures/chateau/pillar_temp_rf
	diffusemap textures/chateau/pillar_temp_rf
	bumpmap textures/chateau/pillar_temp_rf_n
	specularmap textures/chateau/pillar_temp_rf_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/stair_c01
{
    qer_editorimage textures/chateau/stair_c01
	diffusemap textures/chateau/stair_c01
	bumpmap textures/chateau/stair_c01_n
	specularmap textures/chateau/stair_c01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/stair_c03
{
    qer_editormap textures/chateau/stair_c03
	diffusemap textures/chateau/stair_c03
	bumpmap textures/chateau/stair_c03_n
	specularmap textures/chateau/stair_c03_s
	surfaceparm carpetsteps
	implicitMap -
}

textures/chateau/trim_c01
{
    qer_editorimage textures/chateau/trim_c01
	diffusemap textures/chateau/trim_c01
	bumpmap textures/chateau/trim_c01_n
	specularmap textures/chateau/trim_c01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/trim_c03
{
    qer_editorimage textures/chateau/trim_c03
	diffusemap textures/chateau/trim_c03
	bumpmap textures/chateau/trim_c03_n
	specularmap textures/chateau/trim_c03_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/trim_c08
{
    qer_editorimage textures/chateau/trim_c08
	diffusemap textures/chateau/trim_c08
	bumpmap textures/chateau/trim_c08_n
	specularmap textures/chateau/trim_c08_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/trim_c09
{
    qer_editorimage textures/chateau/trim_c09
	diffusemap textures/chateau/trim_c09
	bumpmap textures/chateau/trim_c09_n
	specularmap textures/chateau/trim_c09_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/trim_c10
{
    qer_editorimage textures/chateau/trim_c10
	diffusemap textures/chateau/trim_c10
	bumpmap textures/chateau/trim_c10_n
	specularmap textures/chateau/trim_c10_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/trim_c14
{
    qer_editorimage textures/chateau/trim_c14
	diffusemap textures/chateau/trim_c14
	bumpmap textures/chateau/trim_c14_n
	specularmap textures/chateau/trim_c14_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/walltest_c07a_vertex
{
	qer_editorimage chateau/walltest_c07a
	{
		map textures/chateau/walltest_c07a
		rgbGen vertex
		tcMod Scale .25 .25
	}
}

textures/chateau/window_c03a
{
	qer_editorimage textures/chateau/window_c03a
	q3map_lightimage textures/lightimage/soft_blue
	q3map_lightsubdivide 128
	q3map_surfacelight 300
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c03a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c01.blend
		blendfunc GL_ONE GL_ONE
	}
}

textures/chateau/window_c03a_nolight
{
	qer_editorimage textures/chateau/window_c03a
	implicitMap textures/chateau/window_c03a
}

textures/chateau/window_c03a_750
{
	qer_editorimage textures/chateau/window_c03a
	q3map_lightimage textures/lightimage/soft_blue
	q3map_lightsubdivide 128
	q3map_surfacelight 750
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c03a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c01.blend
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/window_c03a_1250
{
	qer_editorimage textures/chateau/window_c03a
	q3map_lightimage textures/lightimage/soft_blue
	q3map_lightsubdivide 128
	q3map_surfacelight 1250
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c03a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c01.blend
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/window_c03a_2500
{
	qer_editorimage textures/chateau/window_c03a
	q3map_lightimage textures/lightimage/soft_blue
	q3map_lightsubdivide 128
	q3map_surfacelight 2500
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c03a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c01.blend
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/window_c04a
{
	qer_editorimage textures/chateau/window_c04a
	q3map_lightimage textures/lightimage/soft_blue2
	q3map_lightsubdivide 128
	q3map_surfacelight 300
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c04a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c02.blend
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/window_c07a
{
	qer_editorimage textures/chateau/window_c07a
	q3map_lightimage textures/lightimage/soft_warm
	q3map_lightsubdivide 128
	q3map_surfacelight 80
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c07a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c05.blend
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/window_director
{
	qer_editorimage textures/chateau/window_c03a
	q3map_lightimage textures/lightimage/soft_blue
	q3map_lightsubdivide 128
	q3map_surfacelight 3000
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c03a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c01.blend
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/wood_c05
{
    qer_editorimage textures/chateau/wood_c05
	diffusemap textures/chateau/wood_c05
	bumpmap textures/chateau/wood_c05_n
	specularmap textures/chateau/wood_c05_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/wood_c06
{
    qer_editorimage textures/chateau/wood_c06
	diffusemap textures/chateau/wood_c06
	bumpmap textures/chateau/wood_c06_n
	specularmap textures/chateau/wood_c06_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/wood_c07
{
    qer_editorimage textures/chateau/wood_c07
	diffusemap textures/chateau/wood_c07
	bumpmap textures/chateau/wood_c07_n
	specularmap textures/chateau/wood_c07_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/wood_c09
{
    qer_editorimage textures/chateau/wood_c09
	diffusemap textures/chateau/wood_c09
	bumpmap textures/chateau/wood_c09_n
	specularmap textures/chateau/wood_c09_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/wood_c20
{
    qer_editorimage textures/chateau/wood_c20
	diffusemap textures/chateau/wood_c20
	bumpmap textures/chateau/wood_c20_n
	specularmap textures/chateau/wood_c20_s
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/wood_test
{
    qer_editorimage textures/chateau/wood_test
	diffusemap textures/chateau/wood_test
	bumpmap textures/chateau/wood_test_n
	specularmap textures/chateau/wood_test_s
	surfaceparm woodsteps
	implicitMap -
}
