// miltary_wall.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 5 total shaders

textures/miltary_wall/brick_l_01
{
    qer_editorimage textures/miltary_wall/brick_l_01
	diffusemap textures/miltary_wall/brick_l_01
	bumpmap textures/miltary_wall/brick_l_01_n
	specularmap textures/miltary_wall/brick_l_01
	surfaceparm woodsteps
	implicitMap -
}

textures/miltary_wall/miltary_m01
{
    qer_editorimage textures/miltary_wall/miltary_m01
	diffusemap textures/miltary_wall/miltary_m01
	bumpmap textures/miltary_wall/miltary_m01_n
	specularmap textures/miltary_wall/miltary_m01_s
	surfaceparm woodsteps
	implicitMap -
}

textures/miltary_wall/miltary_m06
{
    qer_editorimage textures/miltary_wall/miltary_m06
	diffusemap textures/miltary_wall/miltary_m06
	bumpmap textures/miltary_wall/miltary_m06_n
	specularmap textures/miltary_wall/miltary_m06_s
	surfaceparm woodsteps
	implicitMap -
}

textures/miltary_wall/miltary_m06_cloth
{
    qer_editorimage textures/miltary_wall/miltary_m06
	diffusemap textures/miltary_wall/miltary_m06
	bumpmap textures/miltary_wall/miltary_m06_n
	specularmap textures/miltary_wall/miltary_m06_s

	implicitMap textures/miltary_wall/miltary_m06.tga
}

textures/miltary_wall/mroof_m01a
{
    qer_editorimage textures/miltary_wall/mroof_m01a
	diffusemap textures/miltary_wall/mroof_m01a
	bumpmap textures/miltary_wall/mroof_m01a_n
	specularmap textures/miltary_wall/mroof_m01a_s
	surfaceparm roofsteps
	implicitMap -
}

textures/miltary_wall/window_m03
{
    qer_trans 0.4
    qer_editorimage textures/miltary_wall/window_m03
	diffusemap textures/miltary_wall/window_m03
	bumpmap textures/miltary_wall/window_m03_n
	specularmap textures/miltary_wall/window_m03_s
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm pointlight
	implicitBlend -
}
