// rock.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

textures/rock/dam_m01a
{
    qer_editorimage textures/rock/dam_m01a.tga
	diffusemap textures/rock/dam_m01a.tga
	bumpmap textures/rock/dam_m01a_n.tga
	{
		map textures/rock/dam_m01a.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen identity
	}
}
