// town_roof.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003 updated 2017 thunder
// 1 total shaders

textures/town_roof/roof_c05
{
    qer_editorimage textures/town_roof/roof_c05
    diffusemap textures/town_roof/roof_c05
	specularmap textures/town_roof/roof_c05_s
	bumpmap textures/town_roof/roof_c05_n
	surfaceparm roofsteps
	implicitMap -
}
