// town_wall.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
//updated by thunder 2017
// 3 total shaders

textures/town_wall/store_c01
{
    qer_editorimage textures/town_wall/store_c01
	diffusemap textures/town_wall/store_c01
	specularmap textures/town_wall/store_c01_s
	bumpmap textures/town_wall/store_c01_n
	surfaceparm woodsteps
	implicitMap -
}

textures/town_wall/store_c02
{
    qer_editorimage textures/town_wall/store_c02
	diffusemap textures/town_wall/store_c02
	specularmap textures/town_wall/store_c02_s
	bumpmap textures/town_wall/store_c02_n
	surfaceparm woodsteps
	implicitMap -
}

textures/town_wall/store_c03_a
{
    qer_editorimage textures/town_wall/store_c03_a
	diffusemap textures/town_wall/store_c03_a
	specularmap textures/town_wall/store_c03_a_s
	bumpmap textures/town_wall/store_c03_a_n
	surfaceparm woodsteps
	implicitMap -
}
