// town_props.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

textures/town_props/streetname_c01
{
    qer_editorimage textures/town_props/streetname_c01
	diffusemap textures/town_props/streetname_c01
	specularmap textures/town_props/streetname_c01_s
	bumpmap textures/town_props/streetname_c01_n
	surfaceparm metalsteps
	implicitMap -
}
