// town_wood.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// updated for etl by thunder 2017
// 5 total shaders (was 4)

textures/town_wood/trenchwood
{
    qer_editorimage textures/town_wood/trenchwood
	diffusemap textures/town_wood/trenchwood
	specularmap textures/town_wood/trenchwood_s
	bumpmap textures/town_wood/trenchwood_n
	surfaceparm woodsteps
	implicitMap -
}

textures/town_wood/wood_c01
{
    qer_editorimage textures/town_wood/wood_c01
	diffusemap textures/town_wood/wood_c01
	specularmap textures/town_wood/wood_c01_s
	bumpmap textures/town_wood/wood_c01_n
	surfaceparm woodsteps
	implicitMap -
}

textures/town_wood/wood_c02
{
    qer_editorimage textures/town_wood/wood_c02
	diffusemap textures/town_wood/wood_c02
	specularmap textures/town_wood/wood_c02_s
	bumpmap textures/town_wood/wood_c02_n
	surfaceparm woodsteps
	implicitMap -
}
//NEW!
textures/town_wood/wood_c08
{
    qer_editorimage textures/town_wood/wood_c08
	diffusemap textures/town_wood/wood_c08
	specularmap textures/town_wood/wood_c08_s
	bumpmap textures/town_wood/wood_c08_n
	surfaceparm woodsteps
	implicitMap -
}
// END NEW
textures/town_wood/wood_c11
{
    qer_editorimage textures/town_wood/wood_c11
	diffusemap textures/town_wood/wood_c11
	specularmap textures/town_wood/wood_c11_s
	bumpmap textures/town_wood/wood_c11_n
	surfaceparm woodsteps
	implicitMap -
}
