// tree.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003 ** updated 2017
// 6 total shaders

textures/tree/tree_m02dm
{
    qer_editorimage textures/tree/tree_m02dm
	diffusemap textures/tree/tree_m02dm
	bumpmap textures/tree/tree_m02dm_n
	specularmap textures/tree/tree_m02dm_s
	nopicmip
	cull twosided
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm trans
	implicitMask -
}

textures/tree/tree_m02s
{
    qer_editorimage textures/tree/tree_m02s
	diffusemap textures/tree/tree_m02s
	bumpmap textures/tree/tree_m02s_n
	specularmap textures/tree/tree_m02s_s
	nopicmip
	cull twosided
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm trans
	implicitMask -
}

textures/tree/tree_m07_lod
{
    qer_editorimage textures/tree/tree_m07_lod
	diffusemap textures/tree/tree_m07_lod
	bumpmap textures/tree/tree_m07_lod_n
	specularmap textures/tree/tree_m07_lod_s
	nopicmip
	cull twosided
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm trans
	implicitMask -
}

textures/tree/tree_m08
{
    qer_editorimage textures/tree/tree_m08
	diffusemap textures/tree/tree_m08
	bumpmap textures/tree/tree_m08_n
	specularmap textures/tree/tree_m08_s
	nopicmip
	cull twosided
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm trans
	implicitMask -
}

textures/tree/trunck3
{
    qer_editorimage textures/tree/trunck3
	diffusemap textures/tree/trunck3
	bumpmap textures/tree/trunck3_n
	specularmap textures/tree/trunck3_s
	cull twosided
	surfaceparm nomarks
	{
		map textures/tree/trunck3.tga
		rgbGen identity
	}
}

textures/tree/trunck3a
{
    qer_editorimage textures/tree/trunck3a
	diffusemap textures/tree/trunck3a
	bumpmap textures/tree/trunck3a_n
	specularmap textures/tree/trunck3a_s
	cull twosided
	surfaceparm nomarks
	{
		map textures/tree/trunck3a.tga
		rgbGen identity
	}
}
