// villa_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// updated for ETL by thunder 2017
// 1 total shaders

textures/villa_sd/villawindow_a
{
    qer_editorimage textures/villa_sd/villawindow_a
	diffusemap textures/villa_sd/villawindow_a
	specularmap textures/villa_sd/villawindow_a_s
	bumpmap textures/villa_sd/villawindow_a_n
	surfaceparm alphashadow
	surfaceparm glass
	surfaceparm pointlight
	surfaceparm trans
	{
		map textures/villa_sd/villawindow_a
		blendfunc GL_ONE GL_ONE
		rgbGen vertex
	}
	{
		map textures/villa_sd/villawindow_a
		alphaFunc GE128
		rgbGen vertex
	}
}
