// wood.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
//updated by Thunder for ETL 2017
// 26 total shaders

textures/wood/wood_c01
{
    qer_editorimage textures/wood/wood_c01
	diffusemap textures/wood/wood_c01
	//specularmap textures/wood/wood_c01_s
	bumpmap textures/wood/wood_c01_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m01_usat
{
    qer_editorimage textures/wood/wood_m01_usat
	diffusemap textures/wood/wood_m01_usat
	//specularmap textures/wood/wood_m01_usat_s
	bumpmap textures/wood/wood_m01_usat_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m02
{
    qer_editorimage textures/wood/wood_m02
	diffusemap textures/wood/wood_m02
	//specularmap textures/wood/wood_m02_s
	bumpmap textures/wood/wood_m02_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m02a
{
    qer_editorimage textures/wood/wood_m02a
	diffusemap textures/wood/wood_m02a
	//specularmap textures/wood/wood_m02a_s
	bumpmap textures/wood/wood_m02a_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05
{
    qer_editorimage textures/wood/wood_m05
	diffusemap textures/wood/wood_m05
	//specularmap textures/wood/wood_m05_s
	bumpmap textures/wood/wood_m05_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05_usata
{
    qer_editorimage textures/wood/wood_m05_usata
	diffusemap textures/wood/wood_m05_usata
	//specularmap textures/wood/wood_m05_usata_s
	bumpmap textures/wood/wood_m05_usata_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05a_usat
{
    qer_editorimage textures/wood/wood_m05a_usat
	diffusemap textures/wood/wood_m05a_usat
	//specularmap textures/wood/wood_m05a_usat_s
	bumpmap textures/wood/wood_m05a_usat_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05a_usat_snow
{
    qer_editorimage textures/wood/wood_m05a_usat_snow
	diffusemap textures/wood/wood_m05a_usat_snow
	//specularmap textures/wood/wood_m05a_usat_snow_s
	bumpmap textures/wood/wood_m05a_usat_snow_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05a_usata
{
    qer_editorimage textures/wood/wood_m05a_usata
    diffusemap textures/wood/wood_m05a_usata
	//specularmap textures/wood/wood_m05a_usata_s
	bumpmap textures/wood/wood_m05a_usata_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05a_usata_dm
{
    qer_editorimage textures/wood/wood_m05a_usata_dm
	diffusemap textures/wood/wood_m05a_usata_dm
	//specularmap textures/wood/wood_m05a_usata_dm_s
	bumpmap textures/wood/wood_m05a_usata_dm_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06
{
    qer_editorimage textures/wood/wood_m06
	diffusemap textures/wood/wood_m06
	//specularmap textures/wood/wood_m06_s
	bumpmap textures/wood/wood_m06_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06_usat
{
    qer_editorimage textures/wood/wood_m06_usat
	diffusemap textures/wood/wood_m06_usat
	//specularmap textures/wood/wood_m06_usat_s
	bumpmap textures/wood/wood_m06_usat_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06a
{
    qer_editorimage textures/wood/wood_m06a
	diffusemap textures/wood/wood_m06a
	//specularmap textures/wood/wood_m06a_s
	bumpmap textures/wood/wood_m06a_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06b
{
    qer_editorimage textures/wood/wood_m06b
	diffusemap textures/wood/wood_m06b
	//specularmap textures/wood/wood_m06b_s
	bumpmap textures/wood/wood_m06b_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m08
{
    qer_editorimage textures/wood/wood_m08
	diffusemap textures/wood/wood_m08
	//specularmap textures/wood/wood_m08_s
	bumpmap textures/wood/wood_m08_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m08_usat
{
    qer_editorimage textures/wood/wood_m08_usat
	diffusemap textures/wood/wood_m08_usat
	//specularmap textures/wood/wood_m08_usat_s
	bumpmap textures/wood/wood_m08_usat_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m09
{
    qer_editorimage textures/wood/wood_m09
	diffusemap textures/wood/wood_m09
	//specularmap textures/wood/wood_m09_s
	bumpmap textures/wood/wood_m09_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m09_usat
{
    qer_editorimage textures/wood/wood_m09_usat
	diffusemap textures/wood/wood_m09_usat
	//specularmap textures/wood/wood_m09_usat_s
	bumpmap textures/wood/wood_m09_usat_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m11
{
    qer_editorimage textures/wood/wood_m11
	diffusemap textures/wood/wood_m11
	//specularmap textures/wood/wood_m11_s
	bumpmap textures/wood/wood_m11_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m12
{
    qer_editorimage textures/wood/wood_m12
	diffusemap textures/wood/wood_m12
	//specularmap textures/wood/wood_m12_s
	bumpmap textures/wood/wood_m12_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m12_usat
{
    qer_editorimage textures/wood/wood_m12_usat
	diffusemap textures/wood/wood_m12_usat
	//specularmap textures/wood/wood_m12_usat_s
	bumpmap textures/wood/wood_m12_usat_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m12a
{
	qer_editorimage textures/wood/wood_m12
	diffusemap textures/wood/wood_m12a
	//specularmap textures/wood/wood_m12a_s
	bumpmap textures/wood/wood_m12a_n
	surfaceparm woodsteps
	implicitMap textures/wood/wood_m12
}

textures/wood/wood_m13
{
    qer_editorimage textures/wood/wood_m13
	diffusemap textures/wood/wood_m13
	//specularmap textures/wood/wood_m13_s
	bumpmap textures/wood/wood_m13_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m13_usat
{
    qer_editorimage textures/wood/wood_m13_usat
	diffusemap textures/wood/wood_m13_usat
	//specularmap textures/wood/wood_m13_usat_s
	bumpmap textures/wood/wood_m13_usat_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m16
{
    qer_editorimage textures/wood/wood_m16
	diffusemap textures/wood/wood_m16
	//specularmap textures/wood/wood_m16_s
	bumpmap textures/wood/wood_m16_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m16cm
{
    qer_editorimage textures/wood/wood_m16cm
	diffusemap textures/wood/wood_m16cm
	//specularmap textures/wood/wood_m16cm_s
	bumpmap textures/wood/wood_m16cm_n
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m18
{
    qer_editorimage textures/wood/wood_m18
	diffusemap textures/wood/wood_m18
	//specularmap textures/wood/wood_m18_s
	bumpmap textures/wood/wood_m18_n
	surfaceparm woodsteps
	implicitMap -
}
