// xlab_wall.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 10 total shaders

textures/xlab_wall/x_metalwall_m01
{
    qer_editorimage textures/xlab_wall/x_metalwall_m01
	diffusemap textures/xlab_wall/x_metalwall_m01
	specularmap textures/xlab_wall/x_metalwall_m01_s
	bumpmap textures/xlab_wall/x_metalwall_m01_n
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xmetal_c03
{
    qer_editorimage textures/xlab_wall/xmetal_c03
	diffusemap textures/xlab_wall/xmetal_c03
	specularmap textures/xlab_wall/xmetal_c03_s
	bumpmap textures/xlab_wall/xmetal_c03_n
	surfaceparm metalsteps
	implicitMap -
}

//===========================================================================
// Metal phong for the brushwork only railings in fueldump
//===========================================================================
textures/xlab_wall/xmetal_c03_phong
{
    diffusemap textures/xlab_wall/xmetal_c03
	specularmap textures/xlab_wall/xmetal_c03_s
	bumpmap textures/xlab_wall/xmetal_c03_n
	surfaceparm metalsteps
	q3map_nonplanar
	q3map_shadeangle 179
	qer_editorimage textures/xlab_wall/xmetal_c03_phong
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/xlab_wall/xmetal_c03
		blendFunc filter
	}
}

textures/xlab_wall/xmetal_m02
{
    qer_editorimage textures/xlab_wall/xmetal_m02
	diffusemap textures/xlab_wall/xmetal_m02
	specularmap textures/xlab_wall/xmetal_m02_s
	bumpmap textures/xlab_wall/xmetal_m02_n
	surfaceparm metalsteps
	{
		map textures/effects/tinfx
		rgbGen identity
		tcGen environment
	}
	{
		map textures/xlab_wall/xmetal_m02
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

textures/xlab_wall/xmetal_m02a
{
    qer_editorimage textures/xlab_wall/xmetal_m02a
	diffusemap textures/xlab_wall/xmetal_m02a
	specularmap textures/xlab_wall/xmetal_m02a_s
	bumpmap textures/xlab_wall/xmetal_m02a_n
	surfaceparm metalsteps
	{
		map textures/effects/tinfx
		rgbGen identity
		tcGen environment
	}
	{
		map textures/xlab_wall/xmetal_m02a
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

textures/xlab_wall/xmetal_m02a_trim
{
    qer_editorimage textures/xlab_wall/xmetal_m02a_trim
	diffusemap textures/xlab_wall/xmetal_m02a_trim
	specularmap textures/xlab_wall/xmetal_m02a_trim_s
	bumpmap textures/xlab_wall/xmetal_m02a_trim_n
	surfaceparm metalsteps
	{
		map textures/effects/tinfx
		rgbGen identity
		tcGen environment
	}
	{
		map textures/xlab_wall/xmetal_m02a_trim
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

textures/xlab_wall/xmetal_m02f
{
	qer_editorimage textures/xlab_wall/xmetal_m02
	diffusemap textures/xlab_wall/xmetal_m02f
	specularmap textures/xlab_wall/xmetal_m02f_s
	bumpmap textures/xlab_wall/xmetal_m02f_n
	surfaceparm metalsteps
	implicitMap textures/xlab_wall/xmetal_m02
}

textures/xlab_wall/xmetal_m03l
{
    qer_editorimage textures/xlab_wall/xmetal_m03l
	diffusemap textures/xlab_wall/xmetal_m03l
	specularmap textures/xlab_wall/xmetal_m03l_s
	bumpmap textures/xlab_wall/xmetal_m03l_n
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xtrim_c02
{
    qer_editorimage textures/xlab_wall/xtrim_c02
	diffusemap textures/xlab_wall/xtrim_c02
	specularmap textures/xlab_wall/xtrim_c02_s
	bumpmap textures/xlab_wall/xtrim_c02_n
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xtrim_c04
{
    qer_editorimage textures/xlab_wall/xtrim_c04
	diffusemap textures/xlab_wall/xtrim_c04
	specularmap textures/xlab_wall/xtrim_c04_s
	bumpmap textures/xlab_wall/xtrim_c04_n
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xtrim_c05
{
    qer_editorimage textures/xlab_wall/xtrim_c05
	diffusemap textures/xlab_wall/xtrim_c05
	specularmap textures/xlab_wall/xtrim_c05_s
	bumpmap textures/xlab_wall/xtrim_c05_n
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xtrim_c06
{
    qer_editorimage textures/xlab_wall/xtrim_c06
	diffusemap textures/xlab_wall/xtrim_c06
	specularmap textures/xlab_wall/xtrim_c06_s
	bumpmap textures/xlab_wall/xtrim_c06_n
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xtrim_c07
{
    qer_editorimage textures/xlab_wall/xtrim_c07
	diffusemap textures/xlab_wall/xtrim_c07
	specularmap textures/xlab_wall/xtrim_c07_s
	bumpmap textures/xlab_wall/xtrim_c07_n
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xwall_c07
{
    qer_editorimage textures/xlab_wall/xwall_c07
	diffusemap textures/xlab_wall/xwall_c07
	specularmap textures/xlab_wall/xwall_c07_s
	bumpmap textures/xlab_wall/xwall_c07_n
	surfaceparm metalsteps
	implicitMap -
}
