# 2021 Legacy team
name: LinuxBuildMachine

on:
  push:
    paths:
      - 'misc/docker/build.Dockerfile'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Get the version
        id: vars
        run: |
          echo ::set-output name=tag::$(date +%Y%m%d%H%M%S)

      - name: Build and push the latest Docker image
        run: |
          docker build misc/docker --file misc/docker/build.Dockerfile --tag etlegacy/lnx-build:latest --tag etlegacy/lnx-build:${{steps.vars.outputs.tag}}
          docker push etlegacy/lnx-build:${{steps.vars.outputs.tag}}
          docker push etlegacy/lnx-build:latest
